// Generated by scripts/generate-ordinal-casing.cs on .NET 10.0.12 (invariant globalization). Do not edit.
// 1475 code points in 203 runs, each checked against StringComparison.OrdinalIgnoreCase.

/**
 * .NET's OrdinalIgnoreCase, which System.Text.Json uses for case-insensitive property names and enum names: every
 * code point maps to its simple uppercase from .NET's own Unicode tables — never to JavaScript's full mappings (ß → SS, ﬃ → FFI),
 * and ı / ſ stay as they are. Runs of [start, count, stride, delta].
 */
const RUNS: readonly number[] = [
  0x61, 26, 1, -32, 0xb5, 1, 1, 743, 0xe0, 23, 1, -32, 0xf8, 7, 1, -32, 0xff, 1, 1, 121, 0x101, 24, 2, -1, 0x133, 3, 2, -1, 0x13a, 8, 2, -1,
  0x14b, 23, 2, -1, 0x17a, 3, 2, -1, 0x180, 1, 1, 195, 0x183, 2, 2, -1, 0x188, 1, 1, -1, 0x18c, 1, 1, -1, 0x192, 1, 1, -1, 0x195, 1, 1, 97,
  0x199, 1, 1, -1, 0x19a, 1, 1, 163, 0x19b, 1, 1, 42561, 0x19e, 1, 1, 130, 0x1a1, 3, 2, -1, 0x1a8, 1, 1, -1, 0x1ad, 1, 1, -1, 0x1b0, 1, 1, -1,
  0x1b4, 2, 2, -1, 0x1b9, 1, 1, -1, 0x1bd, 1, 1, -1, 0x1bf, 1, 1, 56, 0x1c5, 1, 1, -1, 0x1c6, 1, 1, -2, 0x1c8, 1, 1, -1, 0x1c9, 1, 1, -2,
  0x1cb, 1, 1, -1, 0x1cc, 1, 1, -2, 0x1ce, 8, 2, -1, 0x1dd, 1, 1, -79, 0x1df, 9, 2, -1, 0x1f2, 1, 1, -1, 0x1f3, 1, 1, -2, 0x1f5, 1, 1, -1,
  0x1f9, 20, 2, -1, 0x223, 9, 2, -1, 0x23c, 1, 1, -1, 0x23f, 2, 1, 10815, 0x242, 1, 1, -1, 0x247, 5, 2, -1, 0x250, 1, 1, 10783, 0x251, 1, 1, 10780,
  0x252, 1, 1, 10782, 0x253, 1, 1, -210, 0x254, 1, 1, -206, 0x256, 2, 1, -205, 0x259, 1, 1, -202, 0x25b, 1, 1, -203, 0x25c, 1, 1, 42319, 0x260, 1, 1, -205,
  0x261, 1, 1, 42315, 0x263, 1, 1, -207, 0x264, 1, 1, 42343, 0x265, 1, 1, 42280, 0x266, 1, 1, 42308, 0x268, 1, 1, -209, 0x269, 1, 1, -211, 0x26a, 1, 1, 42308,
  0x26b, 1, 1, 10743, 0x26c, 1, 1, 42305, 0x26f, 1, 1, -211, 0x271, 1, 1, 10749, 0x272, 1, 1, -213, 0x275, 1, 1, -214, 0x27d, 1, 1, 10727, 0x280, 1, 1, -218,
  0x282, 1, 1, 42307, 0x283, 1, 1, -218, 0x287, 1, 1, 42282, 0x288, 1, 1, -218, 0x289, 1, 1, -69, 0x28a, 2, 1, -217, 0x28c, 1, 1, -71, 0x292, 1, 1, -219,
  0x29d, 1, 1, 42261, 0x29e, 1, 1, 42258, 0x345, 1, 1, 84, 0x371, 2, 2, -1, 0x377, 1, 1, -1, 0x37b, 3, 1, 130, 0x3ac, 1, 1, -38, 0x3ad, 3, 1, -37,
  0x3b1, 17, 1, -32, 0x3c2, 1, 1, -31, 0x3c3, 9, 1, -32, 0x3cc, 1, 1, -64, 0x3cd, 2, 1, -63, 0x3d0, 1, 1, -62, 0x3d1, 1, 1, -57, 0x3d5, 1, 1, -47,
  0x3d6, 1, 1, -54, 0x3d7, 1, 1, -8, 0x3d9, 12, 2, -1, 0x3f0, 1, 1, -86, 0x3f1, 1, 1, -80, 0x3f2, 1, 1, 7, 0x3f3, 1, 1, -116, 0x3f5, 1, 1, -96,
  0x3f8, 1, 1, -1, 0x3fb, 1, 1, -1, 0x430, 32, 1, -32, 0x450, 16, 1, -80, 0x461, 17, 2, -1, 0x48b, 27, 2, -1, 0x4c2, 7, 2, -1, 0x4cf, 1, 1, -15,
  0x4d1, 48, 2, -1, 0x561, 38, 1, -48, 0x10d0, 43, 1, 3008, 0x10fd, 3, 1, 3008, 0x13f8, 6, 1, -8, 0x1c80, 1, 1, -6254, 0x1c81, 1, 1, -6253, 0x1c82, 1, 1, -6244,
  0x1c83, 2, 1, -6242, 0x1c85, 1, 1, -6243, 0x1c86, 1, 1, -6236, 0x1c87, 1, 1, -6181, 0x1c88, 1, 1, 35266, 0x1c8a, 1, 1, -1, 0x1d79, 1, 1, 35332, 0x1d7d, 1, 1, 3814,
  0x1d8e, 1, 1, 35384, 0x1e01, 75, 2, -1, 0x1e9b, 1, 1, -59, 0x1ea1, 48, 2, -1, 0x1f00, 8, 1, 8, 0x1f10, 6, 1, 8, 0x1f20, 8, 1, 8, 0x1f30, 8, 1, 8,
  0x1f40, 6, 1, 8, 0x1f51, 4, 2, 8, 0x1f60, 8, 1, 8, 0x1f70, 2, 1, 74, 0x1f72, 4, 1, 86, 0x1f76, 2, 1, 100, 0x1f78, 2, 1, 128, 0x1f7a, 2, 1, 112,
  0x1f7c, 2, 1, 126, 0x1f80, 8, 1, 8, 0x1f90, 8, 1, 8, 0x1fa0, 8, 1, 8, 0x1fb0, 2, 1, 8, 0x1fb3, 1, 1, 9, 0x1fbe, 1, 1, -7205, 0x1fc3, 1, 1, 9,
  0x1fd0, 2, 1, 8, 0x1fe0, 2, 1, 8, 0x1fe5, 1, 1, 7, 0x1ff3, 1, 1, 9, 0x214e, 1, 1, -28, 0x2170, 16, 1, -16, 0x2184, 1, 1, -1, 0x24d0, 26, 1, -26,
  0x2c30, 48, 1, -48, 0x2c61, 1, 1, -1, 0x2c65, 1, 1, -10795, 0x2c66, 1, 1, -10792, 0x2c68, 3, 2, -1, 0x2c73, 1, 1, -1, 0x2c76, 1, 1, -1, 0x2c81, 50, 2, -1,
  0x2cec, 2, 2, -1, 0x2cf3, 1, 1, -1, 0x2d00, 38, 1, -7264, 0x2d27, 1, 1, -7264, 0x2d2d, 1, 1, -7264, 0xa641, 23, 2, -1, 0xa681, 14, 2, -1, 0xa723, 7, 2, -1,
  0xa733, 31, 2, -1, 0xa77a, 2, 2, -1, 0xa77f, 5, 2, -1, 0xa78c, 1, 1, -1, 0xa791, 2, 2, -1, 0xa794, 1, 1, 48, 0xa797, 10, 2, -1, 0xa7b5, 8, 2, -1,
  0xa7c8, 2, 2, -1, 0xa7cd, 1, 1, -1, 0xa7d1, 1, 1, -1, 0xa7d7, 3, 2, -1, 0xa7f6, 1, 1, -1, 0xab53, 1, 1, -928, 0xab70, 80, 1, -38864, 0xff41, 26, 1, -32,
  0x10428, 40, 1, -40, 0x104d8, 36, 1, -40, 0x10597, 11, 1, -39, 0x105a3, 15, 1, -39, 0x105b3, 7, 1, -39, 0x105bb, 2, 1, -39, 0x10cc0, 51, 1, -64, 0x10d70, 22, 1, -32,
  0x118c0, 32, 1, -32, 0x16e60, 32, 1, -32, 0x1e922, 34, 1, -34,
];

const UPPER: ReadonlyMap<number, number> = (() => {
  const map = new Map<number, number>();
  for (let i = 0; i < RUNS.length; i += 4) {
    for (let k = 0; k < RUNS[i + 1]!; k++) {
      const cp = RUNS[i]! + k * RUNS[i + 2]!;
      map.set(cp, cp + RUNS[i + 3]!);
    }
  }
  return map;
})();

/** The uppercase code point .NET's OrdinalIgnoreCase compares for `cp` (the code point itself when it has none). */
export function ordinalUpperCodePoint(cp: number): number {
  if (cp < 0x80) {
    return cp >= 0x61 && cp <= 0x7a ? cp - 32 : cp;
  }
  return UPPER.get(cp) ?? cp;
}

/** The text with every code point mapped as .NET's OrdinalIgnoreCase does (the UTF-16 length never changes). */
export function ordinalUpper(text: string): string {
  let out = "";
  for (const ch of text) {
    out += String.fromCodePoint(ordinalUpperCodePoint(ch.codePointAt(0)!));
  }
  return out;
}

/** `string.Equals(a, b, StringComparison.OrdinalIgnoreCase)`. */
export function ordinalEqualsIgnoreCase(a: string, b: string): boolean {
  return a === b || (a.length === b.length && ordinalUpper(a) === ordinalUpper(b));
}
