using Tisilia.Contract;
using Tisilia.Generator.Diagnostics;
using Tisilia.Generator.TypeScript;

namespace Tisilia.Generator.Portable;

/// <summary>
/// Emits the TypeScript side of a portable project as one self-contained ES module (no imports, so the Explorer can
/// load it as a raw browser artifact): per definition a domain rule/validator, the request encoder following the
/// canonical writer program, the response decoder following the response program, and a request-input factory that
/// accepts a lossless JSON AST. Every builtin scalar is parsed and written exactly by the module's own
/// prelude (<see cref="PortableTsPrelude"/>), tagged unions dispatch on their discriminator and nested objects follow their programs.
/// </summary>
public sealed class PortableTsGenerator
{
    private readonly LoadedPortableProject _project;
    private readonly DiagnosticBag _bag;
    private readonly List<string> _functions = [];
    private int _counter;

    /// <summary>The definition being emitted: nested models with a definition of their own are delegated to that definition's wire functions.</summary>
    private string? _currentDefinitionId;

    /// <summary>
    /// Which wire a decoder reads: "Response" (what the server writes) or "Request" (what the server reads — the Explorer's typed
    /// input). A nested definition is decoded with its program of the same direction: its request wire may accept what its
    /// response wire never writes (a number for a decimal written as a string).
    /// </summary>
    private string _decodeDirection = "Response";

    private PortableTsGenerator(LoadedPortableProject project, DiagnosticBag bag)
    {
        _project = project;
        _bag = bag;
    }

    public static IReadOnlyList<GeneratedFile> Generate(LoadedPortableProject project, DiagnosticBag bag)
    {
        var g = new PortableTsGenerator(project, bag);
        var baseName = project.Project.ProjectId + ".portable";
        return [new GeneratedFile(baseName + ".js", g.Module()), new GeneratedFile(baseName + ".d.ts", g.Declarations())];
    }

    private static string Camel(LoadedDefinition def) => PortableModel.Camel(def.Definition.Id.Split('.').Last());

    private string Module()
    {
        var w = new CodeWriter();
        w.Line($"// Generated by Tisilia portable codec generator {Pipeline.GeneratorVersion} for project {_project.Project.ProjectId}. Do not edit: owned by tisilia.portable-ownership.json.");
        w.Line("// Self-contained: no imports, so that the module can be served to browsers as a raw artifact.");
        w.Raw(Helpers);
        w.Raw(PortableTsPrelude.Scalars);
        foreach (var def in _project.Definitions.OrderBy(d => d.Definition.Id, StringComparer.Ordinal))
        {
            EmitDefinition(def);
        }

        foreach (var f in _functions)
        {
            w.Line();
            w.Raw(f);
        }

        return w.ToString();
    }

    private const string Helpers = """

        function fail(code, path, message) {
          const e = new Error(message);
          e.name = "CodecError";
          e.code = code;
          e.path = path;
          return e;
        }
        const decimalMax = 79228162514264337593543950335n;
        const integerRanges = {
          int8: [-128n, 127n], uint8: [0n, 255n], int16: [-32768n, 32767n], uint16: [0n, 65535n],
          int32: [-2147483648n, 2147483647n], uint32: [0n, 4294967295n],
          int64: [-9223372036854775808n, 9223372036854775807n], uint64: [0n, 18446744073709551615n],
        };
        function parseInteger(name, text, path) {
          if (!/^-?(?:0|[1-9][0-9]*)$/.test(text)) throw fail("grammar", path, name + " requires an integer lexeme");
          const v = BigInt(text);
          const [min, max] = integerRanges[name];
          if (v < min || v > max) throw fail("range", path, name + " out of range");
          return name === "int64" || name === "uint64" ? v : Number(v);
        }
        function validateInteger(name, value, path) {
          const big = name === "int64" || name === "uint64";
          let v;
          if (typeof value === "bigint") v = value;
          else if (typeof value === "number" && Number.isInteger(value)) v = BigInt(value);
          else throw fail("type-mismatch", path, name + " requires an integer");
          const [min, max] = integerRanges[name];
          if (v < min || v > max) throw fail("range", path, name + " out of range");
          return big ? v : Number(v);
        }
        function parseDecimal(text, path) {
          const m = /^(-?)(0|[1-9][0-9]*)(?:\.([0-9]+))?(?:[eE]([+-]?[0-9]+))?$/.exec(text);
          if (m === null) throw fail("grammar", path, "decimal requires a number lexeme");
          const frac = m[3] ?? "";
          let coefficient = BigInt(m[2] + frac);
          let scale = frac.length - (m[4] === undefined ? 0 : Number.parseInt(m[4], 10));
          while (scale < 0) { coefficient *= 10n; scale++; }
          while (scale > 28) {
            // System.Text.Json rounds beyond 28 fraction digits half away from zero
            const digit = coefficient % 10n; coefficient /= 10n; scale--;
            if (digit >= 5n && scale === 28) coefficient += 1n;
          }
          while (coefficient > decimalMax && scale > 0 && coefficient % 10n === 0n) { coefficient /= 10n; scale--; }
          if (coefficient > decimalMax) throw fail("range", path, "decimal out of the System.Decimal range");
          return { kind: "decimal", sign: m[1] === "-" && coefficient !== 0n ? -1 : 1, coefficient, scale };
        }
        function validateDecimal(value, path) {
          if (typeof value !== "object" || value === null || value.kind !== "decimal" || typeof value.coefficient !== "bigint" || value.coefficient < 0n || value.coefficient > decimalMax || !Number.isInteger(value.scale) || value.scale < 0 || value.scale > 28 || (value.sign !== 1 && value.sign !== -1)) {
            throw fail("type-mismatch", path, "Decimal value required");
          }
          return value;
        }
        function formatDecimal(d) {
          let digits = d.coefficient.toString();
          if (d.scale > 0) { digits = digits.padStart(d.scale + 1, "0"); digits = digits.slice(0, -d.scale) + "." + digits.slice(-d.scale); }
          return d.sign < 0 && d.coefficient !== 0n ? "-" + digits : digits;
        }
        const guidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        function parseGuid(text, path) {
          if (!guidPattern.test(text)) throw fail("grammar", path, "guid must be in 8-4-4-4-12 hexadecimal form");
          return text.toLowerCase();
        }
        function validateGuid(value, path) {
          if (typeof value !== "string") throw fail("type-mismatch", path, "guid requires a string");
          return parseGuid(value, path);
        }
        // String.prototype.isWellFormed is ES2024 (Safari 16.4, Chrome 111, Firefox 119): the module runs in ES2022 browsers
        function isWellFormed(s) {
          for (let i = 0; i < s.length; i++) {
            const c = s.charCodeAt(i);
            if (c >= 0xd800 && c <= 0xdbff) {
              const next = i + 1 < s.length ? s.charCodeAt(i + 1) : -1;
              if (next < 0xdc00 || next > 0xdfff) return false;
              i++;
            } else if (c >= 0xdc00 && c <= 0xdfff) return false;
          }
          return true;
        }
        function validateString(value, path) {
          if (typeof value !== "string" || !isWellFormed(value)) throw fail("type-mismatch", path, "well-formed string required");
          return value;
        }
        function validateBoolean(value, path) {
          if (typeof value !== "boolean") throw fail("type-mismatch", path, "boolean required");
          return value;
        }
        function isJsonValue(v) {
          return typeof v === "object" && v !== null && ["null", "boolean", "string", "number", "array", "object"].includes(v.kind);
        }
        function entryOf(ast, name) {
          for (const e of ast.entries) if (e.name === name) return e;
          return undefined;
        }
        function childPath(path, segment) {
          return path + "/" + String(segment).replace(/~/g, "~0").replace(/\//g, "~1");
        }

        """;

    private void EmitDefinition(LoadedDefinition loaded)
    {
        var def = loaded.Definition;
        _currentDefinitionId = def.Id;
        var camel = Camel(loaded);
        var domainId = def.Request?.DomainTypeId ?? def.Response!.DomainTypeId;
        var validate = EmitValidate(domainId, def.Id);
        var w = new CodeWriter();
        w.Line($"/** {def.Id}@{def.DefinitionVersion}: domain rule / validator of {domainId}. */");
        w.Line($"export function {camel}DomainRule(value, context) {{ return {validate}(value, context.path); }}");
        w.Line($"export const {camel}Validate = {{ validateDomain: {camel}DomainRule }};");
        if (def.Response is { } response)
        {
            var decode = EmitDecode(response.Program, response.DomainTypeId, def.Id, "/response/program");
            w.Line($"export const {camel}ResponseDecode = {{ decodeResponse(wire, context) {{ return {validate}({decode}(wire, context.path), context.path); }} }};");
        }

        if (def.Request is { } request)
        {
            if (loaded.CanonicalWriter is null)
            {
                PortableModel.Unsupported(_bag, "/" + def.Id + "/request", "no canonical writer for the request program", def.Id);
            }
            else
            {
                var encode = EmitEncode(loaded.CanonicalWriter, request.DomainTypeId, def.Id, "/request/writer");
                _decodeDirection = "Request";
                var read = EmitDecode(request.Program, request.DomainTypeId, def.Id, "/request/program");
                _decodeDirection = "Response";
                w.Line($"export const {camel}RequestEncode = {{ encodeRequest(value, context) {{ return {encode}({validate}(value, context.path), context.path); }} }};");
                w.Line($"/** Explorer typed input: a lossless JSON AST of the request wire, read with the request program. */");
                w.Line($"export const {camel}RequestInput = {{ parseRequestInput(input, context) {{ if (typeof input === \"string\") throw fail(\"unsupported\", context.path, \"portable input requires a JSON value editor\"); return {validate}({read}(input, context.path), context.path); }} }};");
            }
        }

        _functions.Add(w.ToString());
    }

    private string Next(string kind) => $"{kind}_{_counter++}";

    // ------------------------------------------------------------------ validation of domain values

    private readonly Dictionary<string, string> _validators = new(StringComparer.Ordinal);

    private string EmitValidate(string typeId, string definitionId)
    {
        if (_validators.TryGetValue(typeId, out var existing))
        {
            return existing;
        }

        var name = Next("validate");
        _validators[typeId] = name;
        var w = new CodeWriter();
        if (typeId.StartsWith("std.", StringComparison.Ordinal) || (_project.Models.GetValueOrDefault(typeId)?.Shape is PrimitiveShape))
        {
            var scalar = typeId.StartsWith("std.", StringComparison.Ordinal) ? typeId["std.".Length..] : PortableModel.ScalarName(((PrimitiveShape)_project.Models[typeId].Shape).PrimitiveId);
            w.Line($"function {name}(value, path) {{ return {ValidateScalarExpression(scalar, "value", "path", definitionId)}; }}");
        }
        else if (_project.Models.TryGetValue(typeId, out var model) && model.Shape is ObjectShape shape)
        {
            var variant = PortableModel.VariantOf(_project, typeId);
            var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
            w.Open($"function {name}(value, path) {{");
            w.Line("if (typeof value !== \"object\" || value === null || Array.isArray(value)) throw fail(\"type-mismatch\", path, \"object required\");");
            w.Line("const out = Object.create(null);");
            foreach (var prop in shape.Properties)
            {
                if (prop.Name == discriminator)
                {
                    // the discriminator of a union variant is a literal
                    w.Line($"if (value[{PortableModel.Quote(prop.Name)}] !== {PortableModel.Quote(variant!.Value.Tag)}) throw fail(\"type-mismatch\", childPath(path, {PortableModel.Quote(prop.Name)}), \"discriminator must be {variant.Value.Tag}\");");
                    w.Line($"out[{PortableModel.Quote(prop.Name)}] = {PortableModel.Quote(variant.Value.Tag)};");
                    continue;
                }

                var inner = EmitValidateUse(prop.Use, definitionId);
                w.Open($"if (Object.prototype.hasOwnProperty.call(value, {PortableModel.Quote(prop.Name)})) {{");
                w.Line($"const v = value[{PortableModel.Quote(prop.Name)}];");
                w.Line($"if (v === undefined) throw fail(\"undefined-not-allowed\", childPath(path, {PortableModel.Quote(prop.Name)}), \"omit the member or set null\");");
                w.Line($"out[{PortableModel.Quote(prop.Name)}] = {inner}(v, childPath(path, {PortableModel.Quote(prop.Name)}));");
                w.Close();
                if (prop.Presence == Presence.Required)
                {
                    w.Line($"else throw fail(\"missing-required\", childPath(path, {PortableModel.Quote(prop.Name)}), \"required member\");");
                }
            }

            w.Line("return out;");
            w.Close();
        }
        else if (model?.Shape is ArrayShape array)
        {
            var element = EmitValidateUse(array.Element, definitionId);
            w.Line($"function {name}(value, path) {{ if (!Array.isArray(value)) throw fail(\"type-mismatch\", path, \"array required\"); const out = []; for (let i = 0; i < value.length; i++) out.push({element}(value[i], childPath(path, i))); return out; }}");
        }
        else if (model?.Shape is UnionShape union)
        {
            var discriminator = PortableModel.DiscriminatorOf(_project, typeId) ?? "kind";
            w.Open($"function {name}(value, path) {{");
            w.Line("if (typeof value !== \"object\" || value === null || Array.isArray(value)) throw fail(\"type-mismatch\", path, \"object required\");");
            w.Open($"switch (value[{PortableModel.Quote(discriminator)}]) {{");
            foreach (var v in union.Variants)
            {
                var inner = EmitValidate(v.Use.TypeId, definitionId);
                w.Line($"case {PortableModel.Quote(v.Tag)}: return {inner}(value, path);");
            }

            w.Line($"default: throw fail(\"type-mismatch\", childPath(path, {PortableModel.Quote(discriminator)}), \"unknown discriminator\");");
            w.Close();
            w.Close();
        }
        else
        {
            PortableModel.Unsupported(_bag, "/" + definitionId, $"domain '{typeId}' has a shape the portable TypeScript generator does not produce", definitionId);
            w.Line($"function {name}(value, path) {{ throw fail(\"unsupported\", path, \"unsupported domain\"); }}");
        }

        _functions.Add(w.ToString());
        return name;
    }

    private string EmitValidateUse(TypeUse use, string definitionId)
    {
        var inner = EmitValidate(use.TypeId, definitionId);
        if (!use.SemanticNullable)
        {
            return inner;
        }

        var name = Next("validateNullable");
        _functions.Add($"function {name}(value, path) {{ return value === null ? null : {inner}(value, path); }}\n");
        return name;
    }

    private string ValidateScalarExpression(string scalar, string v, string path, string definitionId)
    {
        if (!PortableModel.TsSupportedScalars.Contains(scalar))
        {
            PortableModel.Unsupported(_bag, "/" + definitionId, $"'{scalar}' is not a builtin scalar", definitionId);
            return $"(() => {{ throw fail(\"unsupported\", {path}, \"unknown scalar {scalar}\"); }})()";
        }

        return scalar switch
        {
            "string" => $"validateString({v}, {path})",
            "boolean" => $"validateBoolean({v}, {path})",
            "guid" => $"validateGuid({v}, {path})",
            "char" => $"validateChar({v}, {path})",
            "bytes" => $"validateBytes({v}, {path})",
            "decimal" => $"validateDecimal({v}, {path})",
            "float32" or "float64" => $"validateFloat({PortableModel.Quote(scalar)}, {v}, {path})",
            "json-value" => $"(isJsonValue({v}) ? {v} : (() => {{ throw fail(\"type-mismatch\", {path}, \"lossless JsonValue required\"); }})())",
            "date-only" => $"validateDateOnly({v}, {path})",
            "time-only" => $"validateTimeOnly({v}, {path})",
            "datetime-utc" or "datetime-unspecified" => $"validateDateTimeTicks({PortableModel.Quote(scalar)}, {v}, {path})",
            "datetime-local-wire" => $"validateDateTimeLocalWire({v}, {path})",
            "datetime-offset" => $"validateDateTimeOffset({v}, {path})",
            "duration" => $"validateDuration({v}, {path})",
            _ => $"validateInteger({PortableModel.Quote(scalar)}, {v}, {path})",
        };
    }

    /// <summary>Parser of a scalar's canonical string form (the System.Text.Json writer text), or null for non-string scalars.</summary>
    private static string? StringScalarParser(string scalar) => scalar switch
    {
        "string" => "validateString",
        "guid" => "parseGuid",
        "char" => "validateChar",
        "bytes" => "decodeBase64",
        "date-only" => "parseDateOnly",
        "time-only" => "parseTimeOnly",
        "datetime-utc" => "parseDateTimeUtc",
        "datetime-unspecified" => "parseDateTimeUnspecified",
        "datetime-local-wire" => "parseDateTimeLocalWire",
        "datetime-offset" => "parseDateTimeOffset",
        "duration" => "parseDuration",
        _ => null,
    };

    /// <summary>Canonical string writer of a string-wire scalar applied to a validated domain value.</summary>
    private static string? StringScalarFormatter(string scalar, string v) => scalar switch
    {
        "string" or "guid" or "char" => v,
        "bytes" => $"encodeBase64({v})",
        "date-only" => $"formatDateOnly({v})",
        "time-only" => $"formatTimeOnly({v})",
        "datetime-utc" => $"formatDateTimeUtc({v})",
        "datetime-unspecified" => $"formatDateTimeUnspecified({v})",
        "datetime-local-wire" => $"formatDateTimeLocalWire({v})",
        "datetime-offset" => $"formatDateTimeOffset({v})",
        "duration" => $"formatDuration({v})",
        _ => null,
    };

    // ------------------------------------------------------------------ decode (wire AST → domain), following a program

    private string EmitDecode(Program node, string domainTypeId, string definitionId, string path)
    {
        var name = Next("decode");
        var w = new CodeWriter();
        switch (node)
        {
            case ScalarOp scalar:
                w.Line($"function {name}(wire, path) {{ return {DecodeScalarExpression(scalar, definitionId)}; }}");
                break;
            case RefOp reference:
            {
                var target = PortableModel.Ref(_project, reference.DefinitionId);
                w.Line($"function {name}(wire, path) {{ return {(target is null ? "missing" : Camel(target))}{_decodeDirection}DecodeWire(wire, path); }}");
                if (target is not null)
                {
                    EnsureRefDecoders(target);
                }

                break;
            }

            case NullableOp nullable:
            {
                var inner = EmitDecode(nullable.Value, domainTypeId, definitionId, path + "/value");
                w.Line($"function {name}(wire, path) {{ return wire.kind === \"null\" ? null : {inner}(wire, path); }}");
                break;
            }

            case ArrayOp array:
            {
                var elementType = _project.Models.TryGetValue(domainTypeId, out var m) && m.Shape is ArrayShape s ? s.Element.TypeId : domainTypeId;
                var element = EmitDecode(array.Element, elementType, definitionId, path + "/element");
                w.Line($"function {name}(wire, path) {{ if (wire.kind !== \"array\") throw fail(\"type-mismatch\", path, \"array required\"); const out = []; for (let i = 0; i < wire.items.length; i++) out.push({element}(wire.items[i], childPath(path, i))); return out; }}");
                break;
            }

            case ObjectOp obj:
            {
                var model = _project.Models.GetValueOrDefault(domainTypeId);
                if (model is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedRead && nestedRead.Definition.Id != _currentDefinitionId)
                {
                    // a model with a definition of its own (declared or synthesized) is decoded by that definition's wire decoder
                    w.Line($"function {name}(wire, path) {{ return {Camel(nestedRead)}{_decodeDirection}DecodeWire(wire, path); }}");
                    EnsureRefDecoders(nestedRead);
                    break;
                }

                w.Open($"function {name}(wire, path) {{");
                w.Line("if (wire.kind !== \"object\") throw fail(\"type-mismatch\", path, \"object required\");");
                w.Line("const out = Object.create(null); const seen = new Set();");
                w.Open("for (const entry of wire.entries) {");
                w.Line("if (seen.has(entry.name)) throw fail(\"duplicate-property\", childPath(path, entry.name), \"duplicate member\");");
                w.Line("seen.add(entry.name);");
                w.Open("switch (entry.name) {");
                var variant = PortableModel.VariantOf(_project, domainTypeId);
                var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
                if (discriminator is not null)
                {
                    // the discriminator member of a tagged-union branch is a required literal of the tag
                    w.Line($"case {PortableModel.Quote(discriminator)}: if (entry.value.kind !== \"string\" || entry.value.value !== {PortableModel.Quote(variant!.Value.Tag)}) throw fail(\"type-mismatch\", childPath(path, entry.name), \"discriminator must be {variant.Value.Tag}\"); out[{PortableModel.Quote(discriminator)}] = {PortableModel.Quote(variant.Value.Tag)}; break;");
                }

                var i = 0;
                foreach (var member in obj.Members)
                {
                    var prop = (model?.Shape as ObjectShape)?.Properties.FirstOrDefault(p => p.Name == member.Name);
                    var decoder = EmitDecode(member.Node, prop?.Use.TypeId ?? domainTypeId, definitionId, path + "/members/" + i++ + "/node");
                    w.Line($"case {PortableModel.Quote(member.Name)}: out[{PortableModel.Quote(member.Name)}] = {decoder}(entry.value, childPath(path, entry.name)); break;");
                }

                w.Line(obj.UnknownMembers == UnknownMembers.Reject ? "default: throw fail(\"unexpected-property\", childPath(path, entry.name), \"unknown member\");" : "default: break;");
                w.Close();
                w.Close();
                if (discriminator is not null)
                {
                    w.Line($"if (!seen.has({PortableModel.Quote(discriminator)})) throw fail(\"missing-required\", childPath(path, {PortableModel.Quote(discriminator)}), \"discriminator required\");");
                }

                foreach (var member in obj.Members.Where(m => m.Presence == Presence.Required))
                {
                    w.Line($"if (!seen.has({PortableModel.Quote(member.Name)})) throw fail(\"missing-required\", childPath(path, {PortableModel.Quote(member.Name)}), \"required member\");");
                }

                w.Line("return out;");
                w.Close();
                break;
            }

            case TaggedUnionOp tagged:
            {
                var union = _project.Models.GetValueOrDefault(domainTypeId)?.Shape as UnionShape;
                if (union is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedUnion && nestedUnion.Definition.Id != _currentDefinitionId)
                {
                    w.Line($"function {name}(wire, path) {{ return {Camel(nestedUnion)}{_decodeDirection}DecodeWire(wire, path); }}");
                    EnsureRefDecoders(nestedUnion);
                    break;
                }

                w.Open($"function {name}(wire, path) {{");
                w.Line("if (wire.kind !== \"object\") throw fail(\"type-mismatch\", path, \"object required\");");
                w.Line($"const tag = entryOf(wire, {PortableModel.Quote(tagged.Discriminator)});");
                w.Line($"if (tag === undefined || tag.value.kind !== \"string\") throw fail(\"missing-required\", childPath(path, {PortableModel.Quote(tagged.Discriminator)}), \"string discriminator required\");");
                w.Open("switch (tag.value.value) {");
                var i = 0;
                foreach (var branch in tagged.Branches)
                {
                    var variantType = union?.Variants.FirstOrDefault(v => v.Tag == branch.Tag)?.Use.TypeId ?? domainTypeId;
                    var decoder = EmitDecode(branch.Node, variantType, definitionId, path + "/branches/" + i++ + "/node");
                    w.Line($"case {PortableModel.Quote(branch.Tag)}: return {decoder}(wire, path);");
                }

                w.Line($"default: throw fail(\"type-mismatch\", childPath(path, {PortableModel.Quote(tagged.Discriminator)}), \"unknown discriminator\");");
                w.Close();
                w.Close();
                break;
            }

            case TokenUnionOp union:
            {
                w.Open($"function {name}(wire, path) {{");
                w.Open("switch (wire.kind) {");
                var i = 0;
                foreach (var branch in union.Branches)
                {
                    var decoder = EmitDecode(branch.Node, domainTypeId, definitionId, path + "/branches/" + i++ + "/node");
                    w.Line($"case {PortableModel.Quote(branch.Token.ToString().ToLowerInvariant())}: return {decoder}(wire, path);");
                }

                w.Line("default: throw fail(\"type-mismatch\", path, \"token not accepted by the union\");");
                w.Close();
                w.Close();
                break;
            }

            default:
                PortableModel.Unsupported(_bag, path, $"unknown program op '{node.Op}'", definitionId);
                w.Line($"function {name}(wire, path) {{ throw fail(\"unsupported\", path, \"unsupported op\"); }}");
                break;
        }

        _functions.Add(w.ToString());
        return name;
    }

    private readonly HashSet<string> _refDecoders = new(StringComparer.Ordinal);

    /// <summary>Refs call the target definition's wire decoder/encoder (without the outer domain validation, which the caller applies once).</summary>
    private void EnsureRefDecoders(LoadedDefinition target)
    {
        if (!_refDecoders.Add(target.Definition.Id))
        {
            return;
        }

        var camel = Camel(target);
        var w = new CodeWriter();
        // the target's programs are emitted as its own: its model is inline there, everything else delegates again
        var outer = _currentDefinitionId;
        var outerDirection = _decodeDirection;
        _currentDefinitionId = target.Definition.Id;
        _decodeDirection = "Response";
        if (target.Definition.Response is { } response)
        {
            var decode = EmitDecode(response.Program, response.DomainTypeId, target.Definition.Id, "/response/program");
            w.Line($"function {camel}ResponseDecodeWire(wire, path) {{ return {decode}(wire, path); }}");
        }
        else
        {
            w.Line($"function {camel}ResponseDecodeWire(wire, path) {{ throw fail(\"unsupported\", path, \"definition {target.Definition.Id} has no response program\"); }}");
        }

        // the Explorer's typed input of an enclosing definition reads this one with its request program
        _decodeDirection = "Request";
        if (target.Definition.Request is { } request)
        {
            var read = EmitDecode(request.Program, request.DomainTypeId, target.Definition.Id, "/request/program");
            w.Line($"function {camel}RequestDecodeWire(wire, path) {{ return {read}(wire, path); }}");
        }
        else
        {
            w.Line($"function {camel}RequestDecodeWire(wire, path) {{ throw fail(\"unsupported\", path, \"definition {target.Definition.Id} has no request program\"); }}");
        }

        _decodeDirection = outerDirection;

        if (target.CanonicalWriter is { } writer)
        {
            var encode = EmitEncode(writer, (target.Definition.Request ?? target.Definition.Response)!.DomainTypeId, target.Definition.Id, "/request/writer");
            w.Line($"function {camel}RequestEncodeDomain(value, path) {{ return {encode}(value, path); }}");
        }
        else
        {
            w.Line($"function {camel}RequestEncodeDomain(value, path) {{ throw fail(\"unsupported\", path, \"definition {target.Definition.Id} has no request writer\"); }}");
        }

        _currentDefinitionId = outer;
        _functions.Add(w.ToString());
    }

    private string DecodeScalarExpression(ScalarOp scalar, string definitionId)
    {
        var name = PortableModel.ScalarName(scalar.ScalarId);
        if (!PortableModel.TsSupportedScalars.Contains(name))
        {
            PortableModel.Unsupported(_bag, "/" + definitionId, $"'{name}' is not a builtin scalar", definitionId);
            return "(() => { throw fail(\"unsupported\", path, \"unknown scalar\"); })()";
        }

        const string stringRequired = "(() => { throw fail(\"type-mismatch\", path, \"string required\"); })()";
        const string numberRequired = "(() => { throw fail(\"type-mismatch\", path, \"number required\"); })()";
        if (scalar.Representation == ScalarRepresentation.String)
        {
            // number scalars written as JSON strings (the string representation)
            var parse = name switch
            {
                "decimal" => "parseDecimal(wire.value, path)",
                "float32" or "float64" => $"parseFloatLexeme({PortableModel.Quote(name)}, wire.value, path)",
                _ => $"parseInteger({PortableModel.Quote(name)}, wire.value, path)",
            };
            return $"wire.kind === \"string\" ? {parse} : {stringRequired}";
        }

        if (StringScalarParser(name) is { } parser)
        {
            return $"wire.kind === \"string\" ? {parser}(wire.value, path) : {stringRequired}";
        }

        return name switch
        {
            "boolean" => "wire.kind === \"boolean\" ? wire.value : (() => { throw fail(\"type-mismatch\", path, \"boolean required\"); })()",
            "decimal" => $"wire.kind === \"number\" ? parseDecimal(wire.text, path) : {numberRequired}",
            "float32" or "float64" => $"wire.kind === \"number\" ? parseFloatLexeme({PortableModel.Quote(name)}, wire.text, path) : {numberRequired}",
            "json-value" => "wire",
            _ => $"wire.kind === \"number\" ? parseInteger({PortableModel.Quote(name)}, wire.text, path) : {numberRequired}",
        };
    }

    // ------------------------------------------------------------------ encode (domain → wire AST), following the canonical writer

    private string EmitEncode(Program node, string domainTypeId, string definitionId, string path)
    {
        var name = Next("encode");
        var w = new CodeWriter();
        switch (node)
        {
            case ScalarOp scalar:
                w.Line($"function {name}(value, path) {{ return {EncodeScalarExpression(scalar)}; }}");
                break;
            case RefOp reference:
            {
                var target = PortableModel.Ref(_project, reference.DefinitionId);
                w.Line($"function {name}(value, path) {{ return {(target is null ? "missing" : Camel(target))}RequestEncodeDomain(value, path); }}");
                if (target is not null)
                {
                    EnsureRefDecoders(target);
                }

                break;
            }

            case NullableOp nullable:
            {
                var inner = EmitEncode(nullable.Value, domainTypeId, definitionId, path + "/value");
                w.Line($"function {name}(value, path) {{ return value === null ? {{ kind: \"null\" }} : {inner}(value, path); }}");
                break;
            }

            case ArrayOp array:
            {
                var elementType = _project.Models.TryGetValue(domainTypeId, out var m) && m.Shape is ArrayShape s ? s.Element.TypeId : domainTypeId;
                var element = EmitEncode(array.Element, elementType, definitionId, path + "/element");
                w.Line($"function {name}(value, path) {{ const items = []; for (let i = 0; i < value.length; i++) items.push({element}(value[i], childPath(path, i))); return {{ kind: \"array\", items }}; }}");
                break;
            }

            case ObjectOp obj:
            {
                var model = _project.Models.GetValueOrDefault(domainTypeId);
                if (model is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedWrite && nestedWrite.Definition.Id != _currentDefinitionId)
                {
                    w.Line($"function {name}(value, path) {{ return {Camel(nestedWrite)}RequestEncodeDomain(value, path); }}");
                    EnsureRefDecoders(nestedWrite);
                    break;
                }

                w.Open($"function {name}(value, path) {{");
                w.Line("const entries = [];");
                var variant = PortableModel.VariantOf(_project, domainTypeId);
                if (variant is not null && PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id) is { } discriminator)
                {
                    // the union writes the discriminator first, as System.Text.Json writes polymorphic metadata
                    w.Line($"entries.push({{ name: {PortableModel.Quote(discriminator)}, value: {{ kind: \"string\", value: {PortableModel.Quote(variant.Value.Tag)} }} }});");
                }

                var i = 0;
                foreach (var member in obj.Members)
                {
                    var prop = (model?.Shape as ObjectShape)?.Properties.FirstOrDefault(p => p.Name == member.Name);
                    var encoder = EmitEncode(member.Node, prop?.Use.TypeId ?? domainTypeId, definitionId, path + "/members/" + i++ + "/node");
                    var access = $"value[{PortableModel.Quote(member.Name)}]";
                    if (member.Presence == Presence.Optional)
                    {
                        w.Line($"if (Object.prototype.hasOwnProperty.call(value, {PortableModel.Quote(member.Name)}) && {access} !== undefined) entries.push({{ name: {PortableModel.Quote(member.Name)}, value: {encoder}({access}, childPath(path, {PortableModel.Quote(member.Name)})) }});");
                    }
                    else
                    {
                        w.Line($"entries.push({{ name: {PortableModel.Quote(member.Name)}, value: {encoder}({access}, childPath(path, {PortableModel.Quote(member.Name)})) }});");
                    }
                }

                w.Line("return { kind: \"object\", entries };");
                w.Close();
                break;
            }

            case TaggedUnionOp tagged:
            {
                var union = _project.Models.GetValueOrDefault(domainTypeId)?.Shape as UnionShape;
                if (union is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedUnionWrite && nestedUnionWrite.Definition.Id != _currentDefinitionId)
                {
                    w.Line($"function {name}(value, path) {{ return {Camel(nestedUnionWrite)}RequestEncodeDomain(value, path); }}");
                    EnsureRefDecoders(nestedUnionWrite);
                    break;
                }

                w.Open($"function {name}(value, path) {{");
                w.Open($"switch (value[{PortableModel.Quote(tagged.Discriminator)}]) {{");
                var i = 0;
                foreach (var branch in tagged.Branches)
                {
                    var variantType = union?.Variants.FirstOrDefault(v => v.Tag == branch.Tag)?.Use.TypeId ?? domainTypeId;
                    var encoder = EmitEncode(branch.Node, variantType, definitionId, path + "/branches/" + i++ + "/node");
                    w.Line($"case {PortableModel.Quote(branch.Tag)}: return {encoder}(value, path);");
                }

                w.Line($"default: throw fail(\"type-mismatch\", childPath(path, {PortableModel.Quote(tagged.Discriminator)}), \"unknown discriminator\");");
                w.Close();
                w.Close();
                break;
            }

            default:
                PortableModel.Unsupported(_bag, path, "the canonical writer cannot contain token unions", definitionId);
                w.Line($"function {name}(value, path) {{ throw fail(\"unsupported\", path, \"unsupported writer op\"); }}");
                break;
        }

        _functions.Add(w.ToString());
        return name;
    }

    private static string EncodeScalarExpression(ScalarOp scalar)
    {
        var name = PortableModel.ScalarName(scalar.ScalarId);
        if (scalar.Representation == ScalarRepresentation.String)
        {
            var text = name switch
            {
                "decimal" => "formatDecimal(value)",
                "float32" or "float64" => $"formatFloat({PortableModel.Quote(name)}, value, path)",
                _ => "value.toString()",
            };
            return $"{{ kind: \"string\", value: {text} }}";
        }

        if (StringScalarFormatter(name, "value") is { } formatted)
        {
            return $"{{ kind: \"string\", value: {formatted} }}";
        }

        return name switch
        {
            "boolean" => "{ kind: \"boolean\", value }",
            "decimal" => "{ kind: \"number\", text: formatDecimal(value) }",
            "float32" or "float64" => $"{{ kind: \"number\", text: formatFloat({PortableModel.Quote(name)}, value, path) }}",
            "json-value" => "value",
            _ => "{ kind: \"number\", text: value.toString() }",
        };
    }

    // ------------------------------------------------------------------ declarations

    private string Declarations()
    {
        var w = new CodeWriter();
        w.Line($"// Generated by Tisilia portable codec generator {Pipeline.GeneratorVersion}. Type declarations of the self-contained module.");
        w.Line("export interface PortableCodecContext { readonly path: string; }");
        w.Line("export type PortableJsonValue = { kind: \"null\" } | { kind: \"boolean\"; value: boolean } | { kind: \"string\"; value: string } | { kind: \"number\"; text: string } | { kind: \"array\"; items: readonly PortableJsonValue[] } | { kind: \"object\"; entries: readonly { name: string; value: PortableJsonValue }[] };");
        w.Line("export interface PortableDecimal { readonly kind: \"decimal\"; readonly sign: -1 | 1; readonly coefficient: bigint; readonly scale: number; }");
        w.Line("export interface PortableDateOnly { readonly kind: \"date-only\"; readonly year: number; readonly month: number; readonly day: number; }");
        w.Line("export interface PortableTimeOnly { readonly kind: \"time-only\"; readonly ticks: bigint; }");
        w.Line("export interface PortableDateTimeUtc { readonly kind: \"datetime-utc\"; readonly ticks: bigint; }");
        w.Line("export interface PortableDateTimeUnspecified { readonly kind: \"datetime-unspecified\"; readonly ticks: bigint; }");
        w.Line("export interface PortableDateTimeLocalWire { readonly kind: \"datetime-local-wire\"; readonly ticks: bigint; readonly offsetMinutes: number; }");
        w.Line("export interface PortableDateTimeOffset { readonly kind: \"datetime-offset\"; readonly ticks: bigint; readonly offsetMinutes: number; }");
        w.Line("export interface PortableDuration { readonly kind: \"duration\"; readonly ticks: bigint; }");
        foreach (var model in _project.Project.Models.OrderBy(m => m.Id, StringComparer.Ordinal))
        {
            if (model.Shape is ObjectShape shape)
            {
                var variant = PortableModel.VariantOf(_project, model.Id);
                var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
                w.Open($"export interface {PortableModel.Pascal(model.TsName)} {{");
                foreach (var prop in shape.Properties)
                {
                    var type = prop.Name == discriminator ? PortableModel.Quote(variant!.Value.Tag) : TsType(prop.Use);
                    w.Line($"readonly {PortableModel.Quote(prop.Name)}{(prop.Presence == Presence.Optional ? "?" : "")}: {type};");
                }

                w.Close();
            }
            else if (model.Shape is UnionShape union)
            {
                w.Line($"export type {PortableModel.Pascal(model.TsName)} = {string.Join(" | ", union.Variants.Select(v => TsType(v.Use)))};");
            }
        }

        foreach (var def in _project.Definitions.OrderBy(d => d.Definition.Id, StringComparer.Ordinal))
        {
            var camel = Camel(def);
            var domain = TsType(new TypeUse { TypeId = (def.Definition.Request ?? def.Definition.Response)!.DomainTypeId, CodecId = "", SemanticNullable = false });
            w.Line($"export function {camel}DomainRule(value: unknown, context: PortableCodecContext): {domain};");
            w.Line($"export const {camel}Validate: {{ validateDomain(value: unknown, context: PortableCodecContext): {domain} }};");
            if (def.Definition.Response is not null)
            {
                w.Line($"export const {camel}ResponseDecode: {{ decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): {domain} }};");
            }

            if (def.Definition.Request is not null)
            {
                w.Line($"export const {camel}RequestEncode: {{ encodeRequest(value: {domain}, context: PortableCodecContext): PortableJsonValue }};");
                w.Line($"export const {camel}RequestInput: {{ parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): {domain} }};");
            }
        }

        return w.ToString();
    }

    private string TsType(TypeUse use)
    {
        string core;
        if (use.TypeId.StartsWith("std.", StringComparison.Ordinal))
        {
            core = PortableModel.TsScalarType(use.TypeId["std.".Length..]);
        }
        else if (_project.Models.TryGetValue(use.TypeId, out var model))
        {
            core = model.Shape switch
            {
                ArrayShape a => $"readonly ({TsType(a.Element)})[]",
                PrimitiveShape p => PortableModel.TsScalarType(PortableModel.ScalarName(p.PrimitiveId)),
                _ => PortableModel.Pascal(model.TsName),
            };
        }
        else
        {
            core = "unknown";
        }

        return use.SemanticNullable ? core + " | null" : core;
    }
}
