using System.Globalization;
using System.Text;
using Tisilia.Contract;
using Tisilia.Generator.Diagnostics;
using PortableDefinition = Tisilia.Documents.PortableDefinition;
using Tisilia.Generator.TypeScript;
using Tisilia.Generator.Validation;

namespace Tisilia.Generator.Portable;

/// <summary>
/// Emits the C# side of a portable project: domain records for the project's object models, one
/// <c>JsonConverter&lt;T&gt;</c> per definition whose Read follows the request program and Write the response program
/// (System.Text.Json reader/writer only, no reflection), and paired registrations (origin <c>portable</c>) that bind the
/// converter, the wires derived from the programs, the module artifacts and the conformance projection/factory.
/// Generation is deterministic; the source compiles only if the projection types exist.
/// </summary>
public sealed class PortableCSharpGenerator
{
    private readonly LoadedPortableProject _project;
    private readonly DiagnosticBag _bag;
    private readonly string _ns;
    private readonly string _tsArtifactPath;

    /// <summary>The definition whose converter/registration is being emitted: its own model is emitted inline, every other model with a definition is delegated to that definition's converter.</summary>
    private string? _currentDefinitionId;

    private PortableCSharpGenerator(LoadedPortableProject project, string tsArtifactPath, DiagnosticBag bag)
    {
        _project = project;
        _bag = bag;
        _ns = PortableModel.Namespace(project.Project.ProjectId);
        _tsArtifactPath = tsArtifactPath;
    }

    /// <summary>Generates the C# files; <c>tsArtifactPath</c> is the generated TypeScript module relative to the application content root (recorded in the registrations).</summary>
    public static IReadOnlyList<GeneratedFile> Generate(LoadedPortableProject project, string tsArtifactPath, DiagnosticBag bag)
    {
        var g = new PortableCSharpGenerator(project, tsArtifactPath, bag);
        var files = new List<GeneratedFile> { new("Domain.g.cs", g.DomainFile()) };
        foreach (var def in project.Definitions.OrderBy(d => d.Definition.Id, StringComparer.Ordinal))
        {
            files.Add(new GeneratedFile(g.ConverterName(def) + ".g.cs", g.ConverterFile(def)));
        }

        files.Add(new GeneratedFile("Registrations.g.cs", g.RegistrationsFile()));
        return files;
    }

    private static string Header => $"// <auto-generated>\n// Generated by Tisilia portable codec generator {Pipeline.GeneratorVersion}. Do not edit: owned by tisilia.portable-ownership.json.\n// </auto-generated>\n#nullable enable\n";

    private string ConverterName(LoadedDefinition def) => PortableModel.Pascal(def.Definition.Id.Split('.').Last()) + "PortableConverter";

    private string DomainTypeName(string domainTypeId)
    {
        if (_project.Models.TryGetValue(domainTypeId, out var model))
        {
            return _ns + "." + PortableModel.Pascal(model.TsName);
        }

        return PortableModel.CsScalarType(domainTypeId["std.".Length..]) ?? "object";
    }

    // ------------------------------------------------------------------ types

    private string CsType(TypeUse use)
    {
        string core;
        if (use.TypeId.StartsWith("std.", StringComparison.Ordinal))
        {
            core = PortableModel.CsScalarType(use.TypeId["std.".Length..]) ?? "object";
        }
        else if (_project.Models.TryGetValue(use.TypeId, out var model))
        {
            core = model.Shape switch
            {
                ArrayShape a => $"System.Collections.Generic.IReadOnlyList<{CsType(a.Element)}>",
                PrimitiveShape p => PortableModel.CsScalarType(PortableModel.ScalarName(p.PrimitiveId)) ?? "object",
                _ => DomainTypeName(use.TypeId),
            };
        }
        else
        {
            core = "object";
        }

        return use.SemanticNullable ? core + "?" : core;
    }

    private bool IsValueType(TypeUse use)
    {
        if (use.TypeId.StartsWith("std.", StringComparison.Ordinal))
        {
            return PortableModel.IsCsValueType(use.TypeId["std.".Length..]);
        }

        return _project.Models.TryGetValue(use.TypeId, out var m) && m.Shape is PrimitiveShape p && PortableModel.IsCsValueType(PortableModel.ScalarName(p.PrimitiveId));
    }

    private string DomainFile()
    {
        var w = new CodeWriter();
        w.Raw(Header);
        w.Line($"namespace {_ns};");
        w.Line();
        foreach (var model in _project.Project.Models.OrderBy(m => m.Id, StringComparer.Ordinal))
        {
            if (model.Shape is UnionShape)
            {
                w.Line($"/// <summary>{model.Id} ({model.ClrIdentity}): tagged union. The variant records derive from it; the converter dispatches on the discriminator when reading and on the runtime type when writing.</summary>");
                if (ConverterAttribute(model) is { } unionAttribute)
                {
                    w.Line(unionAttribute);
                }

                w.Line($"public abstract record {PortableModel.Pascal(model.TsName)};");
                w.Line();
                continue;
            }

            if (model.Shape is not ObjectShape shape)
            {
                continue;
            }

            var unions = _project.Models.Values.Where(m => m.Shape is UnionShape u && u.Variants.Any(v => v.Use.TypeId == model.Id)).OrderBy(m => m.Id, StringComparer.Ordinal).ToList();
            if (unions.Count > 1)
            {
                _bag.Error(TisiliaCodes.PortableResponseUnion, "SV42", "/models", $"model '{model.Id}' is a variant of {unions.Count} union models; a C# record can derive from one union record only", unions.Select(u => u.Id).ToList());
            }

            var variant = PortableModel.VariantOf(_project, model.Id);
            var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
            // the discriminator of a variant is not a record member: the union converter reads it to dispatch and writes it from the runtime type
            var members = shape.Properties.Where(p => p.Name != discriminator).ToList();
            var required = members.Where(p => p.Presence == Presence.Required).ToList();
            var optional = members.Where(p => p.Presence == Presence.Optional).ToList();
            var parameters = required.Select(p => $"{CsType(p.Use)} {PortableModel.CsIdentifier(p.Name)}")
                .Concat(optional.Select(p => $"{CsType(p.Use with { SemanticNullable = true })} {PortableModel.CsIdentifier(p.Name)} = null"));
            var variantNote = variant is null ? "" : $" Variant '{variant.Value.Tag}' of {variant.Value.Union.Id}: the discriminator '{discriminator}' is implicit.";
            w.Line($"/// <summary>{model.Id} ({model.ClrIdentity}); optional members are null when absent (a nullable optional member is written and projected as null, a non-nullable one is omitted).{variantNote}</summary>");
            if (ConverterAttribute(model) is { } attribute)
            {
                w.Line(attribute);
            }

            var baseType = variant is null ? "" : " : " + PortableModel.Pascal(variant.Value.Union.TsName);
            w.Line($"public sealed record {PortableModel.Pascal(model.TsName)}({string.Join(", ", parameters)}){baseType};");
            w.Line();
        }

        return w.ToString();
    }

    /// <summary>
    /// The <c>[JsonConverter]</c> attribute of the single definition whose CLR type is the model. System.Text.Json picks a property
    /// attribute, then options converters, then the type attribute, so the generated converter is the default wherever the type is
    /// serialized while the runner's domain factory can still override it through options.
    /// </summary>
    private string? ConverterAttribute(Model model)
    {
        var owners = _project.DefinitionsById.Values.Where(d => d.Definition.ClrType == model.ClrIdentity).OrderBy(d => d.Definition.Id, StringComparer.Ordinal).ToList();
        if (owners.Count == 1)
        {
            return $"[System.Text.Json.Serialization.JsonConverter(typeof({PortableModel.Namespace(owners[0].ProjectId)}.{ConverterName(owners[0])}))]";
        }

        if (owners.Count > 1)
        {
            _bag.Warning(TisiliaCodes.PortableProject, "SV42", "/models", $"model '{model.Id}' is the CLR type of {owners.Count} definitions; no [JsonConverter] attribute is generated, register one converter explicitly", owners.Select(o => o.Definition.Id).ToList());
        }

        return null;
    }

    // ------------------------------------------------------------------ converters

    private string ConverterFile(LoadedDefinition loaded)
    {
        var def = loaded.Definition;
        _currentDefinitionId = def.Id;
        var name = ConverterName(loaded);
        var clr = def.ClrType;
        var request = def.Request;
        var response = def.Response;
        var domainRequest = request is null ? null : DomainTypeName(request.DomainTypeId);
        var domainResponse = response is null ? null : DomainTypeName(response.DomainTypeId);
        var methods = new List<string>();
        var counter = 0;
        var w = new CodeWriter();
        w.Raw(Header);
        w.Line("using System.Globalization;");
        w.Line("using System.Text.Json;");
        w.Line("using System.Text.Json.Serialization;");
        w.Line("using Tisilia.Contract;");
        w.Line("using Tisilia.Generator.Conformance;");
        w.Line();
        w.Line($"namespace {_ns};");
        w.Line();
        w.Line($"/// <summary>Portable definition {def.Id}@{def.DefinitionVersion}: Read = request program, Write = response program.</summary>");
        w.Open($"public sealed class {name} : JsonConverter<{clr}> {{");
        w.Line($"public const string DefinitionId = {PortableModel.Quote(def.Id)};");
        w.Line();
        if (request is not null)
        {
            var read = EmitRead(request.Program, request.DomainTypeId, methods, ref counter, def.Id, "/request/program");
            w.Line($"public override {clr} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => {ToClr(request.ProjectionId, $"ReadRequest(ref reader, options)")};");
            w.Line();
            w.Line($"internal static {domainRequest} ReadRequest(ref Utf8JsonReader reader, JsonSerializerOptions options) => {read}(ref reader, options);");
        }
        else
        {
            w.Line($"public override {clr} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new JsonException(\"portable definition '{def.Id}' has no request program: the server does not read this type\");");
        }

        w.Line();
        if (response is not null)
        {
            var write = EmitWrite(response.Program, response.DomainTypeId, methods, ref counter, def.Id, "/response/program");
            w.Line($"public override void Write(Utf8JsonWriter writer, {clr} value, JsonSerializerOptions options) => WriteResponse(writer, {ToDomain(response.ProjectionId, "value")}, options);");
            w.Line();
            w.Line($"internal static void WriteResponse(Utf8JsonWriter writer, {domainResponse} value, JsonSerializerOptions options) => {write}(writer, value, options);");
        }
        else
        {
            w.Line($"public override void Write(Utf8JsonWriter writer, {clr} value, JsonSerializerOptions options) => throw new JsonException(\"portable definition '{def.Id}' has no response program: the server does not write this type\");");
        }

        // conformance projection/factory over the domain: the same for both directions when the domains agree
        var domainId = request?.DomainTypeId ?? response!.DomainTypeId;
        var domainName = DomainTypeName(domainId);
        w.Line();
        w.Line($"internal static JsonValue ProjectDomain({domainName} value) => {EmitProject(domainId, methods, ref counter)}(value);");
        w.Line($"internal static {domainName} ConstructDomain(JsonValue ast) => {EmitConstruct(domainId, methods, ref counter)}(ast);");
        w.Line();
        w.Line("private static JsonException Unexpected(string expected, JsonTokenType actual) => new($\"expected {expected} but found {actual}\");");
        w.Line();
        w.Line("// Utf8JsonReader.GetSingle/GetDouble return ±Infinity for lexemes beyond the binary range (verified against the .NET 10 source); portable readers reject them");
        w.Line("private static float FiniteSingle(float value) => float.IsFinite(value) ? value : throw new JsonException(\"float32 lexeme is outside the binary32 range\");");
        w.Line("private static double FiniteDouble(double value) => double.IsFinite(value) ? value : throw new JsonException(\"float64 lexeme is outside the binary64 range\");");
        w.Line();
        w.Line("// string representation: the string content must be exactly one JSON number lexeme and is read with the Utf8JsonReader rules");
        w.Line("// of the number form, so grammar and range failures are codec failures (JsonException → 400), never a FormatException escaping as a 500");
        w.Line("private static Utf8JsonReader NumberLexeme(string text, string scalar)");
        w.Line("{");
        w.Line("  var bytes = System.Text.Encoding.UTF8.GetBytes(text);");
        w.Line("  var lexeme = new Utf8JsonReader(bytes, isFinalBlock: true, state: default);");
        w.Line("  bool number;");
        w.Line("  try { number = lexeme.Read() && lexeme.TokenType == JsonTokenType.Number; } catch (JsonException) { number = false; }");
        w.Line("  if (!number || lexeme.TokenStartIndex != 0 || lexeme.BytesConsumed != bytes.Length) throw new JsonException(scalar + \" string form must be a JSON number lexeme\");");
        w.Line("  return lexeme;");
        w.Line("}");
        foreach (var (scalar, lexemeClr, get) in new[]
        {
            ("int8", "sbyte", "GetSByte"), ("uint8", "byte", "GetByte"), ("int16", "short", "GetInt16"), ("uint16", "ushort", "GetUInt16"),
            ("int32", "int", "GetInt32"), ("uint32", "uint", "GetUInt32"), ("int64", "long", "GetInt64"), ("uint64", "ulong", "GetUInt64"),
            ("decimal", "decimal", "GetDecimal"), ("float32", "float", "GetSingle"), ("float64", "double", "GetDouble"),
        })
        {
            w.Line($"private static {lexemeClr} {LexemeReaderName(scalar)}(string text) {{ var lexeme = NumberLexeme(text, \"{scalar}\"); try {{ return lexeme.{get}(); }} catch (FormatException e) {{ throw new JsonException(\"{scalar} string form is outside the {scalar} range\", e); }} }}");
        }

        foreach (var m in methods)
        {
            w.Line();
            w.Raw(m);
        }

        w.Close();
        return w.ToString();
    }

    private string ToClr(string projectionId, string domainExpression) => projectionId == Builtins.ProjectionIdentity ? domainExpression : $"{ProjectionClass(projectionId)}.ToClr({domainExpression})";

    private string ToDomain(string projectionId, string clrExpression) => projectionId == Builtins.ProjectionIdentity ? clrExpression : $"{ProjectionClass(projectionId)}.ToDomain({clrExpression})";

    private string ProjectionClass(string projectionId)
    {
        var projection = _project.Project.Projections.FirstOrDefault(p => p.Id == projectionId) ?? _project.Imports.SelectMany(i => i.Project.Projections).FirstOrDefault(p => p.Id == projectionId);
        if (projection?.DotnetImplementation is ModuleImpl m)
        {
            return m.ExportName; // a static class with ToClr/ToDomain, checked when the source compiles
        }

        _bag.Error(TisiliaCodes.ProjectionMismatch, "SV22", "/projections", $"projection '{projectionId}' has no dotnet module implementation", [projectionId]);
        return "MissingProjection";
    }

    private static string MethodName(string kind, ref int counter) => $"{kind}_{counter++}";

    private string EmitRead(Program node, string domainTypeId, List<string> methods, ref int counter, string definitionId, string path)
    {
        var name = MethodName("Read", ref counter);
        var type = DomainTypeName(domainTypeId);
        var w = new CodeWriter();
        switch (node)
        {
            case ScalarOp scalar:
                w.Line($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) => {ReadScalarExpression(scalar)};");
                break;
            case RefOp reference:
            {
                var target = PortableModel.Ref(_project, reference.DefinitionId);
                if (target?.Definition.Request is null)
                {
                    PortableModel.Unsupported(_bag, path, $"ref '{reference.DefinitionId}' has no request program to read with", definitionId);
                }

                w.Line($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) => {(target is null ? "Missing" : ConverterName(target))}.ReadRequest(ref reader, options);");
                break;
            }

            case NullableOp nullable:
            {
                var inner = EmitRead(nullable.Value, domainTypeId, methods, ref counter, definitionId, path + "/value");
                w.Line($"private static {type}? {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) => reader.TokenType == JsonTokenType.Null ? null : {inner}(ref reader, options);");
                break;
            }

            case ArrayOp array:
            {
                if (!_project.Models.TryGetValue(domainTypeId, out var model) || model.Shape is not ArrayShape shape)
                {
                    PortableModel.Unsupported(_bag, path, "array op without an array model", definitionId);
                    break;
                }

                var element = EmitRead(array.Element, shape.Element.TypeId, methods, ref counter, definitionId, path + "/element");
                var elementType = CsType(shape.Element);
                w.Open($"private static System.Collections.Generic.IReadOnlyList<{elementType}> {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) {{");
                w.Line("if (reader.TokenType != JsonTokenType.StartArray) throw Unexpected(\"array\", reader.TokenType);");
                w.Line($"var list = new System.Collections.Generic.List<{elementType}>();");
                w.Open("while (reader.Read() && reader.TokenType != JsonTokenType.EndArray) {");
                w.Line(shape.Element.SemanticNullable ? $"list.Add({element}(ref reader, options));" : $"list.Add({element}(ref reader, options));");
                w.Close();
                w.Line("if (reader.TokenType != JsonTokenType.EndArray) throw new JsonException(\"unexpected end of array\");");
                w.Line("return list;");
                w.Close();
                break;
            }

            case ObjectOp obj:
            {
                if (!_project.Models.TryGetValue(domainTypeId, out var model) || model.Shape is not ObjectShape shape)
                {
                    PortableModel.Unsupported(_bag, path, "object op without an object model", definitionId);
                    break;
                }

                if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedRead && nestedRead.Definition.Id != _currentDefinitionId)
                {
                    // a model with a definition of its own (declared or synthesized from this program) is read by that definition's converter
                    if (nestedRead.Definition.Request is null)
                    {
                        PortableModel.Unsupported(_bag, path, $"model '{domainTypeId}' has no request program to read with", definitionId);
                    }

                    w.Line($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) => {ConverterName(nestedRead)}.ReadRequest(ref reader, options);");
                    break;
                }

                var members = new List<(ObjectMember Member, DomainProperty Property, string Reader)>();
                var i = 0;
                foreach (var member in obj.Members)
                {
                    var prop = shape.Properties.First(p => p.Name == member.Name);
                    members.Add((member, prop, EmitRead(member.Node, prop.Use.TypeId, methods, ref counter, definitionId, path + "/members/" + i + "/node")));
                    i++;
                }

                var variant = PortableModel.VariantOf(_project, domainTypeId);
                var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
                w.Open($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) {{");
                w.Line("if (reader.TokenType != JsonTokenType.StartObject) throw Unexpected(\"object\", reader.TokenType);");
                foreach (var (member, prop, _) in members)
                {
                    var holder = CsType(prop.Use with { SemanticNullable = true });
                    w.Line($"{holder} v_{PortableModel.Camel(member.Name)} = null; var s_{PortableModel.Camel(member.Name)} = false;");
                }

                if (discriminator is not null)
                {
                    w.Line("var s_discriminator = false;");
                }

                w.Open("while (true) {");
                w.Line("if (!reader.Read()) throw new JsonException(\"unexpected end of object\");");
                w.Line("if (reader.TokenType == JsonTokenType.EndObject) break;");
                w.Line("var memberName = reader.GetString()!;");
                w.Line("if (!reader.Read()) throw new JsonException(\"unexpected end of object\");");
                w.Open("switch (memberName) {");
                if (discriminator is not null)
                {
                    // the discriminator of a tagged-union branch is a required literal of the tag
                    w.Line($"case {PortableModel.Quote(discriminator)}: if (s_discriminator) throw new JsonException(\"duplicate member '{discriminator}'\"); s_discriminator = true; if (reader.TokenType != JsonTokenType.String || reader.GetString() != {PortableModel.Quote(variant!.Value.Tag)}) throw new JsonException(\"discriminator '{discriminator}' must be '{variant.Value.Tag}'\"); break;");
                }

                foreach (var (member, prop, reader) in members)
                {
                    var v = PortableModel.Camel(member.Name);
                    w.Line($"case {PortableModel.Quote(member.Name)}: if (s_{v}) throw new JsonException(\"duplicate member '{member.Name}'\"); s_{v} = true; v_{v} = {reader}(ref reader, options); break;");
                }

                // the serializer hands a converter the whole JSON scope, so TrySkip always succeeds here
                w.Line(obj.UnknownMembers == UnknownMembers.Reject ? "default: throw new JsonException($\"unknown member '{memberName}'\");" : "default: if (!reader.TrySkip()) throw new JsonException(\"unexpected end of object\"); break;");
                w.Close();
                w.Close();
                if (discriminator is not null)
                {
                    w.Line($"if (!s_discriminator) throw new JsonException(\"missing discriminator '{discriminator}'\");");
                }

                foreach (var (member, _, _) in members.Where(m => m.Member.Presence == Presence.Required))
                {
                    w.Line($"if (!s_{PortableModel.Camel(member.Name)}) throw new JsonException(\"missing required member '{member.Name}'\");");
                }

                var args = new List<string>();
                foreach (var (member, prop, _) in members)
                {
                    var v = "v_" + PortableModel.Camel(member.Name);
                    string expr;
                    if (member.Presence == Presence.Optional || prop.Use.SemanticNullable)
                    {
                        expr = v;
                    }
                    else if (IsValueType(prop.Use))
                    {
                        expr = v + "!.Value";
                    }
                    else
                    {
                        expr = v + "!";
                    }

                    args.Add($"{PortableModel.CsIdentifier(member.Name)}: {expr}");
                }

                w.Line($"return new {type}({string.Join(", ", args)});");
                w.Close();
                break;
            }

            case TokenUnionOp union:
            {
                w.Open($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) {{");
                w.Open("switch (reader.TokenType) {");
                var i = 0;
                foreach (var branch in union.Branches)
                {
                    var reader = EmitRead(branch.Node, domainTypeId, methods, ref counter, definitionId, path + "/branches/" + i++ + "/node");
                    var cases = branch.Token switch
                    {
                        JsonToken.Number => "case JsonTokenType.Number:",
                        JsonToken.String => "case JsonTokenType.String:",
                        JsonToken.Boolean => "case JsonTokenType.True: case JsonTokenType.False:",
                        JsonToken.Object => "case JsonTokenType.StartObject:",
                        JsonToken.Array => "case JsonTokenType.StartArray:",
                        JsonToken.Null => "case JsonTokenType.Null:",
                        _ => throw new InvalidOperationException(),
                    };
                    w.Line($"{cases} return {reader}(ref reader, options);");
                }

                w.Line("default: throw Unexpected(\"one of the declared tokens\", reader.TokenType);");
                w.Close();
                w.Close();
                break;
            }

            case TaggedUnionOp tagged:
            {
                var union = _project.Models.GetValueOrDefault(domainTypeId)?.Shape as UnionShape;
                if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedUnion && nestedUnion.Definition.Id != _currentDefinitionId)
                {
                    if (nestedUnion.Definition.Request is null)
                    {
                        PortableModel.Unsupported(_bag, path, $"model '{domainTypeId}' has no request program to read with", definitionId);
                    }

                    w.Line($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) => {ConverterName(nestedUnion)}.ReadRequest(ref reader, options);");
                    break;
                }

                w.Open($"private static {type} {name}(ref Utf8JsonReader reader, JsonSerializerOptions options) {{");
                w.Line("if (reader.TokenType != JsonTokenType.StartObject) throw Unexpected(\"object\", reader.TokenType);");
                w.Line("// the discriminator may appear anywhere: look ahead on a copy of the reader (a struct; the serializer buffers the whole object for a converter)");
                w.Line("var probe = reader;");
                w.Line("string? tag = null;");
                w.Open("while (probe.Read() && probe.TokenType != JsonTokenType.EndObject) {");
                w.Line("var probeName = probe.GetString()!;");
                w.Line("if (!probe.Read()) throw new JsonException(\"unexpected end of object\");");
                w.Line($"if (probeName == {PortableModel.Quote(tagged.Discriminator)}) {{ if (probe.TokenType != JsonTokenType.String) throw new JsonException(\"discriminator '{tagged.Discriminator}' must be a string\"); tag = probe.GetString(); break; }}");
                w.Line("if (!probe.TrySkip()) throw new JsonException(\"unexpected end of object\");");
                w.Close();
                w.Open("switch (tag) {");
                var i = 0;
                foreach (var branch in tagged.Branches)
                {
                    var variantType = union?.Variants.FirstOrDefault(v => v.Tag == branch.Tag)?.Use.TypeId ?? domainTypeId;
                    var reader = EmitRead(branch.Node, variantType, methods, ref counter, definitionId, path + "/branches/" + i++ + "/node");
                    w.Line($"case {PortableModel.Quote(branch.Tag)}: return {reader}(ref reader, options);");
                }

                w.Line($"case null: throw new JsonException(\"missing discriminator '{tagged.Discriminator}'\");");
                w.Line("default: throw new JsonException($\"unknown discriminator '{tag}'\");");
                w.Close();
                w.Close();
                break;
            }
        }

        methods.Add(w.ToString());
        return name;
    }

    /// <summary>Name of the generated helper that reads a string-represented number scalar (<c>Int32Lexeme</c>, <c>DecimalLexeme</c>, …).</summary>
    private static string LexemeReaderName(string scalar) => char.ToUpperInvariant(scalar[0]) + scalar[1..] + "Lexeme";

    private static string ReadScalarExpression(ScalarOp scalar)
    {
        var name = PortableModel.ScalarName(scalar.ScalarId);
        if (scalar.Representation == ScalarRepresentation.String)
        {
            // the string content is read as one JSON number lexeme (same grammar and range rules as the number form)
            var parse = name switch
            {
                "int8" or "uint8" or "int16" or "uint16" or "int32" or "uint32" or "int64" or "uint64" or "decimal" => $"{LexemeReaderName(name)}(reader.GetString()!)",
                "float32" => $"FiniteSingle({LexemeReaderName(name)}(reader.GetString()!))",
                "float64" => $"FiniteDouble({LexemeReaderName(name)}(reader.GetString()!))",
                _ => throw new InvalidOperationException("string representation of a non-number scalar"),
            };
            return $"reader.TokenType == JsonTokenType.String ? {parse} : throw Unexpected(\"string\", reader.TokenType)";
        }

        return name switch
        {
            "string" => "reader.TokenType == JsonTokenType.String ? reader.GetString()! : throw Unexpected(\"string\", reader.TokenType)",
            "boolean" => "reader.TokenType is JsonTokenType.True or JsonTokenType.False ? reader.GetBoolean() : throw Unexpected(\"boolean\", reader.TokenType)",
            "int8" => "reader.TokenType == JsonTokenType.Number ? reader.GetSByte() : throw Unexpected(\"number\", reader.TokenType)",
            "uint8" => "reader.TokenType == JsonTokenType.Number ? reader.GetByte() : throw Unexpected(\"number\", reader.TokenType)",
            "int16" => "reader.TokenType == JsonTokenType.Number ? reader.GetInt16() : throw Unexpected(\"number\", reader.TokenType)",
            "uint16" => "reader.TokenType == JsonTokenType.Number ? reader.GetUInt16() : throw Unexpected(\"number\", reader.TokenType)",
            "int32" => "reader.TokenType == JsonTokenType.Number ? reader.GetInt32() : throw Unexpected(\"number\", reader.TokenType)",
            "uint32" => "reader.TokenType == JsonTokenType.Number ? reader.GetUInt32() : throw Unexpected(\"number\", reader.TokenType)",
            "int64" => "reader.TokenType == JsonTokenType.Number ? reader.GetInt64() : throw Unexpected(\"number\", reader.TokenType)",
            "uint64" => "reader.TokenType == JsonTokenType.Number ? reader.GetUInt64() : throw Unexpected(\"number\", reader.TokenType)",
            "decimal" => "reader.TokenType == JsonTokenType.Number ? reader.GetDecimal() : throw Unexpected(\"number\", reader.TokenType)",
            "float32" => "reader.TokenType == JsonTokenType.Number ? FiniteSingle(reader.GetSingle()) : throw Unexpected(\"number\", reader.TokenType)",
            "float64" => "reader.TokenType == JsonTokenType.Number ? FiniteDouble(reader.GetDouble()) : throw Unexpected(\"number\", reader.TokenType)",
            // strings on the wire with System.Text.Json's own canonical parsers
            _ => $"reader.TokenType == JsonTokenType.String || \"{name}\" == \"json-value\" ? JsonSerializer.Deserialize<{PortableModel.CsScalarType(name)}>(ref reader, options)! : throw Unexpected(\"string\", reader.TokenType)",
        };
    }

    private string EmitWrite(Program node, string domainTypeId, List<string> methods, ref int counter, string definitionId, string path)
    {
        var name = MethodName("Write", ref counter);
        var type = DomainTypeName(domainTypeId);
        var w = new CodeWriter();
        switch (node)
        {
            case ScalarOp scalar:
                w.Line($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) => {WriteScalarStatement(scalar)};");
                break;
            case RefOp reference:
            {
                var target = PortableModel.Ref(_project, reference.DefinitionId);
                if (target?.Definition.Response is null)
                {
                    PortableModel.Unsupported(_bag, path, $"ref '{reference.DefinitionId}' has no response program to write with", definitionId);
                }

                w.Line($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) => {(target is null ? "Missing" : ConverterName(target))}.WriteResponse(writer, value, options);");
                break;
            }

            case NullableOp nullable:
            {
                var inner = EmitWrite(nullable.Value, domainTypeId, methods, ref counter, definitionId, path + "/value");
                w.Open($"private static void {name}(Utf8JsonWriter writer, {type}? value, JsonSerializerOptions options) {{");
                w.Line("if (value is null) { writer.WriteNullValue(); return; }");
                w.Line($"{inner}(writer, value{(IsValueTypeName(type) ? ".Value" : "")}, options);");
                w.Close();
                break;
            }

            case ArrayOp array:
            {
                if (!_project.Models.TryGetValue(domainTypeId, out var model) || model.Shape is not ArrayShape shape)
                {
                    PortableModel.Unsupported(_bag, path, "array op without an array model", definitionId);
                    break;
                }

                var element = EmitWrite(array.Element, shape.Element.TypeId, methods, ref counter, definitionId, path + "/element");
                w.Open($"private static void {name}(Utf8JsonWriter writer, System.Collections.Generic.IReadOnlyList<{CsType(shape.Element)}> value, JsonSerializerOptions options) {{");
                w.Line("writer.WriteStartArray();");
                w.Line($"foreach (var item in value) {element}(writer, item, options);");
                w.Line("writer.WriteEndArray();");
                w.Close();
                break;
            }

            case ObjectOp obj:
            {
                if (!_project.Models.TryGetValue(domainTypeId, out var model) || model.Shape is not ObjectShape shape)
                {
                    PortableModel.Unsupported(_bag, path, "object op without an object model", definitionId);
                    break;
                }

                if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedWrite && nestedWrite.Definition.Id != _currentDefinitionId)
                {
                    if (nestedWrite.Definition.Response is null)
                    {
                        PortableModel.Unsupported(_bag, path, $"model '{domainTypeId}' has no response program to write with", definitionId);
                    }

                    w.Line($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) => {ConverterName(nestedWrite)}.WriteResponse(writer, value, options);");
                    break;
                }

                w.Open($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) {{");
                w.Line("writer.WriteStartObject();");
                if (PortableModel.VariantOf(_project, domainTypeId) is { } variant && PortableModel.DiscriminatorOf(_project, variant.Union.Id) is { } discriminator)
                {
                    // the union writes the discriminator first, as System.Text.Json writes polymorphic metadata
                    w.Line($"writer.WriteString({PortableModel.Quote(discriminator)}, {PortableModel.Quote(variant.Tag)});");
                }

                var i = 0;
                foreach (var member in obj.Members)
                {
                    var prop = shape.Properties.First(p => p.Name == member.Name);
                    var writer = EmitWrite(member.Node, prop.Use.TypeId, methods, ref counter, definitionId, path + "/members/" + i++ + "/node");
                    var access = "value." + PortableModel.CsIdentifier(member.Name).TrimStart('@');
                    if (member.Presence == Presence.Optional && !prop.Use.SemanticNullable)
                    {
                        // the C# record has no absent state: a null non-nullable optional member is the absent member and is omitted
                        w.Open($"if ({access} is not null) {{");
                        w.Line($"writer.WritePropertyName({PortableModel.Quote(member.Name)});");
                        w.Line($"{writer}(writer, {access}{(IsValueType(prop.Use) ? ".Value" : "")}, options);");
                        w.Close();
                    }
                    else
                    {
                        // a nullable optional member is present and null when the record member is null, as the CLR projection of any object shows it
                        w.Line($"writer.WritePropertyName({PortableModel.Quote(member.Name)});");
                        w.Line($"{writer}(writer, {access}, options);");
                    }
                }

                w.Line("writer.WriteEndObject();");
                w.Close();
                break;
            }

            case TokenUnionOp:
                PortableModel.Unsupported(_bag, path, "token unions cannot be written (response programs must have a unique writer)", definitionId);
                w.Line($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) => throw new NotSupportedException();");
                break;
            case TaggedUnionOp tagged:
            {
                var union = _project.Models.GetValueOrDefault(domainTypeId)?.Shape as UnionShape;
                if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedUnionWrite && nestedUnionWrite.Definition.Id != _currentDefinitionId)
                {
                    if (nestedUnionWrite.Definition.Response is null)
                    {
                        PortableModel.Unsupported(_bag, path, $"model '{domainTypeId}' has no response program to write with", definitionId);
                    }

                    w.Line($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) => {ConverterName(nestedUnionWrite)}.WriteResponse(writer, value, options);");
                    break;
                }

                w.Open($"private static void {name}(Utf8JsonWriter writer, {type} value, JsonSerializerOptions options) {{");
                w.Open("switch (value) {");
                var i = 0;
                foreach (var branch in tagged.Branches)
                {
                    var variantType = union?.Variants.FirstOrDefault(v => v.Tag == branch.Tag)?.Use.TypeId ?? domainTypeId;
                    var writer = EmitWrite(branch.Node, variantType, methods, ref counter, definitionId, path + "/branches/" + i + "/node");
                    w.Line($"case {DomainTypeName(variantType)} v{i}: {writer}(writer, v{i}, options); break;");
                    i++;
                }

                w.Line("default: throw new JsonException($\"value of type '{value.GetType().Name}' is not a declared variant\");");
                w.Close();
                w.Close();
                break;
            }
        }

        methods.Add(w.ToString());
        return name;
    }

    private static bool IsValueTypeName(string csType) => csType is "bool" or "char" or "sbyte" or "byte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "decimal" or "float" or "double" || csType.StartsWith("System.", StringComparison.Ordinal) && csType is not "System.Text.Json.JsonElement" && !csType.Contains("IReadOnlyList", StringComparison.Ordinal) || csType == "System.Text.Json.JsonElement";

    private static string WriteScalarStatement(ScalarOp scalar)
    {
        var name = PortableModel.ScalarName(scalar.ScalarId);
        if (scalar.Representation == ScalarRepresentation.String)
        {
            return name is "float32" or "float64"
                ? "writer.WriteStringValue(value.ToString(\"R\", CultureInfo.InvariantCulture))"
                : "writer.WriteStringValue(value.ToString(CultureInfo.InvariantCulture))";
        }

        return name switch
        {
            "string" => "writer.WriteStringValue(value)",
            "boolean" => "writer.WriteBooleanValue(value)",
            "int8" or "uint8" or "int16" or "uint16" or "int32" or "uint32" or "int64" or "uint64" or "decimal" or "float32" or "float64" => "writer.WriteNumberValue(value)",
            _ => "JsonSerializer.Serialize(writer, value, options)",
        };
    }

    // ------------------------------------------------------------------ conformance projection / factory

    private string EmitProject(string domainTypeId, List<string> methods, ref int counter)
    {
        var name = MethodName("Project", ref counter);
        var type = DomainTypeName(domainTypeId);
        var w = new CodeWriter();
        if (domainTypeId.StartsWith("std.", StringComparison.Ordinal) || (_project.Models.GetValueOrDefault(domainTypeId)?.Shape is PrimitiveShape))
        {
            var scalar = domainTypeId.StartsWith("std.", StringComparison.Ordinal) ? domainTypeId["std.".Length..] : PortableModel.ScalarName(((PrimitiveShape)_project.Models[domainTypeId].Shape).PrimitiveId);
            w.Line($"private static JsonValue {name}({type} value) => {ProjectScalarExpression(scalar, "value")};");
        }
        else if (_project.Models.TryGetValue(domainTypeId, out var model) && model.Shape is ObjectShape shape)
        {
            var variant = PortableModel.VariantOf(_project, domainTypeId);
            var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
            w.Open($"private static JsonValue {name}({type} value) {{");
            w.Line("var entries = new System.Collections.Generic.List<JsonObjectEntry>();");
            foreach (var prop in shape.Properties)
            {
                if (prop.Name == discriminator)
                {
                    // the discriminator is projected first from the variant tag (unions carry the discriminator first)
                    w.Line($"entries.Add(new JsonObjectEntry {{ Name = {PortableModel.Quote(prop.Name)}, Value = DomainAst.String({PortableModel.Quote(variant!.Value.Tag)}) }});");
                    continue;
                }

                var access = "value." + PortableModel.CsIdentifier(prop.Name).TrimStart('@');
                var inner = EmitProjectUse(prop.Use, methods, ref counter);
                if (prop.Presence == Presence.Optional && !prop.Use.SemanticNullable)
                {
                    // a null non-nullable optional member is absent and omitted from the projected AST; nullable members project as null
                    w.Line($"if ({access} is not null) entries.Add(new JsonObjectEntry {{ Name = {PortableModel.Quote(prop.Name)}, Value = {inner}({access}{(IsValueType(prop.Use) ? ".Value" : "")}) }});");
                }
                else
                {
                    w.Line($"entries.Add(new JsonObjectEntry {{ Name = {PortableModel.Quote(prop.Name)}, Value = {inner}({access}) }});");
                }
            }

            w.Line("return new JsonObjectValue { Entries = entries };");
            w.Close();
        }
        else if (model?.Shape is ArrayShape array)
        {
            var element = EmitProjectUse(array.Element, methods, ref counter);
            w.Line($"private static JsonValue {name}(System.Collections.Generic.IReadOnlyList<{CsType(array.Element)}> value) => new JsonArrayValue {{ Items = value.Select(v => {element}(v)).ToList() }};");
        }
        else if (model?.Shape is UnionShape union)
        {
            w.Open($"private static JsonValue {name}({type} value) {{");
            w.Open("switch (value) {");
            var i = 0;
            foreach (var v in union.Variants)
            {
                var inner = EmitProjectUse(v.Use, methods, ref counter);
                w.Line($"case {DomainTypeName(v.Use.TypeId)} v{i}: return {inner}(v{i});");
                i++;
            }

            w.Line("default: throw new InvalidOperationException($\"value of type '{value.GetType().Name}' is not a declared variant\");");
            w.Close();
            w.Close();
        }
        else
        {
            w.Line($"private static JsonValue {name}({type} value) => throw new NotSupportedException();");
        }

        methods.Add(w.ToString());
        return name;
    }

    private string EmitProjectUse(TypeUse use, List<string> methods, ref int counter)
    {
        // models with a definition (declared or synthesized) project through that definition's converter; a self reference is a static call too
        var inner = _project.Models.TryGetValue(use.TypeId, out var m) && m.Shape is ObjectShape or UnionShape && PortableModel.DefinitionOfModel(_project, use.TypeId) is { } def
            ? ConverterName(def) + ".ProjectDomain"
            : EmitProject(use.TypeId, methods, ref counter);
        if (!use.SemanticNullable)
        {
            return inner;
        }

        var name = MethodName("ProjectNullable", ref counter);
        var type = CsType(use);
        var w = new CodeWriter();
        w.Line($"private static JsonValue {name}({type} value) => value is null ? new JsonNullValue() : {inner}(value{(IsValueType(use) ? ".Value" : "")});");
        methods.Add(w.ToString());
        return name;
    }

    private static string ProjectScalarExpression(string scalar, string v) => scalar switch
    {
        "string" => $"DomainAst.String({v})",
        "char" => $"DomainAst.String({v}.ToString())",
        "boolean" => $"DomainAst.Boolean({v})",
        "guid" => $"DomainAst.String(DomainAst.FormatGuid({v}))",
        "bytes" => $"DomainAst.String(Convert.ToBase64String({v}))",
        "json-value" => $"DomainAst.FromElement({v})",
        "int8" or "uint8" or "int16" or "uint16" or "int32" or "uint32" or "int64" or "uint64" => $"DomainAst.Number({v}.ToString(CultureInfo.InvariantCulture))",
        "decimal" => $"DomainAst.Number(DomainAst.FormatDecimal({v}))",
        "float32" => $"DomainAst.Float32({v})",
        "float64" => $"DomainAst.Float64({v})",
        _ => $"DomainAst.String(DomainAst.StjText({v}))",
    };

    private string EmitConstruct(string domainTypeId, List<string> methods, ref int counter)
    {
        var name = MethodName("Construct", ref counter);
        var type = DomainTypeName(domainTypeId);
        var w = new CodeWriter();
        if (domainTypeId.StartsWith("std.", StringComparison.Ordinal) || (_project.Models.GetValueOrDefault(domainTypeId)?.Shape is PrimitiveShape))
        {
            w.Line($"private static {type} {name}(JsonValue ast) => JsonSerializer.Deserialize<{type}>(DomainAst.ToJsonText(ast), global::Tisilia.TisiliaJson.Plain)!;");
        }
        else if (_project.Models.TryGetValue(domainTypeId, out var model) && model.Shape is ObjectShape shape)
        {
            var variant = PortableModel.VariantOf(_project, domainTypeId);
            var discriminator = variant is null ? null : PortableModel.DiscriminatorOf(_project, variant.Value.Union.Id);
            // the discriminator entry of a variant is dispatch information, not a record member
            var members = shape.Properties.Where(p => p.Name != discriminator).ToList();
            w.Open($"private static {type} {name}(JsonValue ast) {{");
            w.Line("if (ast is not JsonObjectValue obj) throw new FormatException(\"object AST required\");");
            foreach (var prop in members)
            {
                w.Line($"{CsType(prop.Use with { SemanticNullable = true })} v_{PortableModel.Camel(prop.Name)} = null;");
            }

            if (members.Count > 0)
            {
                w.Open("foreach (var entry in obj.Entries) {");
                w.Open("switch (entry.Name) {");
                foreach (var prop in members)
                {
                    var inner = EmitConstructUse(prop.Use, methods, ref counter);
                    w.Line($"case {PortableModel.Quote(prop.Name)}: v_{PortableModel.Camel(prop.Name)} = {inner}(entry.Value); break;");
                }

                w.Close();
                w.Close();
            }

            var args = members.Select(p =>
            {
                var v = "v_" + PortableModel.Camel(p.Name);
                var expr = p.Presence == Presence.Optional || p.Use.SemanticNullable ? v : v + " ?? throw new FormatException(\"missing " + p.Name + "\")";
                return $"{PortableModel.CsIdentifier(p.Name)}: {expr}";
            });
            w.Line($"return new {type}({string.Join(", ", args)});");
            w.Close();
        }
        else if (model?.Shape is ArrayShape array)
        {
            var element = EmitConstructUse(array.Element, methods, ref counter);
            w.Line($"private static System.Collections.Generic.IReadOnlyList<{CsType(array.Element)}> {name}(JsonValue ast) => ast is JsonArrayValue arr ? arr.Items.Select(i => {element}(i)).ToList() : throw new FormatException(\"array AST required\");");
        }
        else if (model?.Shape is UnionShape union)
        {
            var discriminator = PortableModel.DiscriminatorOf(_project, domainTypeId) ?? "kind";
            w.Open($"private static {type} {name}(JsonValue ast) {{");
            w.Line("if (ast is not JsonObjectValue obj) throw new FormatException(\"object AST required\");");
            w.Line($"var tag = DomainAst.Entry(obj, {PortableModel.Quote(discriminator)}) is JsonStringValue s ? s.Value : throw new FormatException(\"missing discriminator '{discriminator}'\");");
            w.Open("switch (tag) {");
            foreach (var v in union.Variants)
            {
                var inner = EmitConstructUse(v.Use, methods, ref counter);
                w.Line($"case {PortableModel.Quote(v.Tag)}: return {inner}(ast);");
            }

            w.Line("default: throw new FormatException($\"unknown discriminator '{tag}'\");");
            w.Close();
            w.Close();
        }
        else
        {
            w.Line($"private static {type} {name}(JsonValue ast) => throw new NotSupportedException();");
        }

        methods.Add(w.ToString());
        return name;
    }

    private string EmitConstructUse(TypeUse use, List<string> methods, ref int counter)
    {
        var inner = _project.Models.TryGetValue(use.TypeId, out var m) && m.Shape is ObjectShape or UnionShape && PortableModel.DefinitionOfModel(_project, use.TypeId) is { } def
            ? ConverterName(def) + ".ConstructDomain"
            : EmitConstruct(use.TypeId, methods, ref counter);
        if (!use.SemanticNullable)
        {
            return inner;
        }

        var name = MethodName("ConstructNullable", ref counter);
        var w = new CodeWriter();
        w.Line($"private static {CsType(use)} {name}(JsonValue ast) => ast is JsonNullValue ? null : {inner}(ast);");
        methods.Add(w.ToString());
        return name;
    }

    // ------------------------------------------------------------------ registrations

    private string RegistrationsFile()
    {
        var w = new CodeWriter();
        w.Raw(Header);
        w.Line("using Tisilia.AspNetCore.Bindings;");
        w.Line("using Tisilia.Contract;");
        w.Line("using Tisilia.Generator.Building;");
        w.Line("using Tisilia.Generator.Validation;");
        w.Line();
        w.Line($"namespace {_ns};");
        w.Line();
        w.Line($"/// <summary>Registrations of the portable module '{_project.Project.ProjectId}': TisiliaOptions.Codecs.AddPaired(...) for each.</summary>");
        w.Open($"public static class {PortableModel.Pascal(_project.Project.ProjectId)}Registrations {{");
        w.Line($"public const string ModuleId = {PortableModel.Quote(_project.Project.ProjectId)};");
        w.Line($"/// <summary>The generated TypeScript module, relative to the application's content root.</summary>");
        w.Line($"public const string TypescriptArtifact = {PortableModel.Quote(_tsArtifactPath)};");
        w.Line();
        w.Line("public static System.Collections.Generic.IReadOnlyList<PairedCodecRegistration> All(string contentRoot) =>");
        w.Line("[");
        foreach (var def in _project.Definitions.OrderBy(d => d.Definition.Id, StringComparer.Ordinal))
        {
            w.Line($"    {PortableModel.Pascal(def.Definition.Id.Split('.').Last())}(contentRoot),");
        }

        w.Line("];");
        w.Line();
        // the path is part of the contract and its semantic hash, so it must not depend on the host that loaded the assembly (dotnet run:
        // the project's bin/<configuration>/<tfm>/, a test host: its own output folder); conformance checks the artifact there (SV44)
        w.Line("// the project's own build output (bin/<configuration>/<tfm>/) whichever host loaded the assembly: the path is hashed into the contract");
        w.Open("private static string AssemblyArtifactPath(string contentRoot, System.Reflection.Assembly assembly) {");
        w.Line("var name = System.IO.Path.GetFileName(assembly.Location);");
        w.Line("var configuration = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<System.Reflection.AssemblyConfigurationAttribute>(assembly)?.Configuration;");
        w.Line("var framework = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<System.Runtime.Versioning.TargetFrameworkAttribute>(assembly)?.FrameworkName;");
        w.Open("if (configuration is not null && framework is not null) {");
        w.Line("var version = new System.Runtime.Versioning.FrameworkName(framework).Version;");
        w.Line("var output = $\"bin/{configuration}/net{version.Major}.{version.Minor}/{name}\";");
        w.Open("if (System.IO.File.Exists(System.IO.Path.Combine(contentRoot, output))) {");
        w.Line("return output;");
        w.Close();
        w.Close();
        w.Line("var relative = System.IO.Path.GetRelativePath(contentRoot, assembly.Location).Replace('\\\\', '/');");
        w.Line("return relative.StartsWith(\"..\", System.StringComparison.Ordinal) || System.IO.Path.IsPathRooted(relative) ? \"bin/\" + name : relative;");
        w.Close();
        foreach (var def in _project.Definitions.OrderBy(d => d.Definition.Id, StringComparer.Ordinal))
        {
            w.Line();
            EmitRegistration(w, def);
        }

        w.Close();
        return w.ToString();
    }

    private void EmitRegistration(CodeWriter w, LoadedDefinition loaded)
    {
        var def = loaded.Definition;
        _currentDefinitionId = def.Id;
        var converter = ConverterName(loaded);
        var modelId = def.Request?.DomainTypeId ?? def.Response!.DomainTypeId;
        var model = _project.Models.GetValueOrDefault(modelId);
        var equivalence = _project.Project.Equivalences.Concat(_project.SynthesizedEquivalences).FirstOrDefault(e => e.Id == (def.Response ?? def.Request)!.EquivalenceId);
        var shortName = PortableModel.Pascal(def.Id.Split('.').Last());
        var camel = PortableModel.Camel(def.Id.Split('.').Last());
        w.Open($"public static PairedCodecRegistration {shortName}(string contentRoot) => new() {{");
        w.Line($"ClrType = typeof({def.ClrType}),");
        w.Line($"ConverterType = typeof({converter}),");
        w.Line($"ModelId = {PortableModel.Quote(modelId)},");
        w.Line($"TsName = {PortableModel.Quote(model?.TsName ?? shortName)},");
        w.Line("Origin = CodecOrigin.Portable,");
        w.Line("BuiltinOracles = true,");
        w.Line($"Shape = f => {ShapeExpression(modelId)},");
        w.Line("ModuleId = ModuleId,");
        w.Line($"ModuleVersion = {PortableModel.Quote(def.DefinitionVersion)},");
        w.Line("License = \"MIT\",");
        w.Line("Artifacts =");
        w.Line("[");
        w.Line($"    new ModuleArtifactSpec(ArtifactTarget.Dotnet, AssemblyArtifactPath(contentRoot, typeof({converter}).Assembly), Bytes: () => System.IO.File.ReadAllBytes(typeof({converter}).Assembly.Location)),");
        w.Line("    new ModuleArtifactSpec(ArtifactTarget.Browser, TypescriptArtifact, Bytes: () => System.IO.File.ReadAllBytes(System.IO.Path.Combine(contentRoot, TypescriptArtifact))),");
        w.Line("    new ModuleArtifactSpec(ArtifactTarget.Node, TypescriptArtifact, Bytes: () => System.IO.File.ReadAllBytes(System.IO.Path.Combine(contentRoot, TypescriptArtifact))),");
        w.Line("],");
        w.Line($"DotnetConverterExport = {PortableModel.Quote(converter)},");
        w.Line($"DomainRuleExport = {PortableModel.Quote(camel + "DomainRule")},");
        w.Line("DotnetOracleExport = \"\",");
        w.Line("TypescriptOracleExport = \"\",");
        // wire ids follow the structural convention <typeId>.read / <typeId>.write so that nested models and refs resolve by name
        if (def.Request is { } request)
        {
            w.Line($"Request = new PairedDirection(Wire: f => {WireExpression(request.Program, modelId, WireDirection.ServerRead, modelId + ".read", def.Id)}, CodecExport: {PortableModel.Quote(camel + "RequestEncode")}, ValidateExport: {PortableModel.Quote(camel + "Validate")}, RequestInputExport: {PortableModel.Quote(camel + "RequestInput")}),");
        }

        if (def.Response is { } response)
        {
            w.Line($"Response = new PairedDirection(Wire: f => {WireExpression(response.Program, modelId, WireDirection.ServerWrite, modelId + ".write", def.Id)}, CodecExport: {PortableModel.Quote(camel + "ResponseDecode")}, ValidateExport: {PortableModel.Quote(camel + "Validate")}),");
        }

        w.Line("ConverterContext = [],");
        w.Line($"SettingsText = {PortableModel.Quote($"portable:{def.Id}@{def.DefinitionVersion}")},");
        w.Line($"Grade = Grade.{equivalence?.Grade.ToString() ?? "G2"},");
        w.Line($"Preserved = [{string.Join(", ", (equivalence?.Preserved ?? ["value"]).Select(PortableModel.Quote))}],");
        w.Line($"NotPreserved = [{string.Join(", ", (equivalence?.NotPreserved ?? []).Select(PortableModel.Quote))}],");
        w.Line($"Project = value => {converter}.ProjectDomain(({DomainTypeName(modelId)})value),");
        w.Line($"Construct = ast => {converter}.ConstructDomain(ast),");
        var dependencies = ReferencedDefinitions(def).Where(d => d.Definition.Id != def.Id).Select(d => $"typeof({d.Definition.ClrType})").Distinct(StringComparer.Ordinal).ToList();
        if (dependencies.Count > 0)
        {
            w.Line($"Dependencies = [{string.Join(", ", dependencies)}],");
        }

        w.Close("};");
    }

    /// <summary>Definitions a definition's programs depend on: refs, and the (declared or synthesized) definitions of nested object/union models.</summary>
    private IEnumerable<LoadedDefinition> ReferencedDefinitions(PortableDefinition def)
    {
        var found = new Dictionary<string, LoadedDefinition>(StringComparer.Ordinal);
        foreach (var direction in new[] { def.Request, def.Response })
        {
            if (direction is not null)
            {
                Collect(direction.Program, direction.DomainTypeId);
            }
        }

        return found.Values.Where(d => d.Definition.Id != def.Id).OrderBy(d => d.Definition.Id, StringComparer.Ordinal);

        void Collect(Program node, string domainTypeId)
        {
            switch (node)
            {
                case RefOp r:
                    if (PortableModel.Ref(_project, r.DefinitionId) is { } target)
                    {
                        found[target.Definition.Id] = target;
                    }

                    break;
                case NullableOp n:
                    Collect(n.Value, domainTypeId);
                    break;
                case ArrayOp a:
                    if (_project.Models.GetValueOrDefault(domainTypeId)?.Shape is ArrayShape array)
                    {
                        Collect(a.Element, array.Element.TypeId);
                    }

                    break;
                case ObjectOp o:
                {
                    if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nested && nested.Definition.Id != def.Id)
                    {
                        found[nested.Definition.Id] = nested;
                    }

                    if (_project.Models.GetValueOrDefault(domainTypeId)?.Shape is ObjectShape shape)
                    {
                        foreach (var m in o.Members)
                        {
                            if (shape.Properties.FirstOrDefault(p => p.Name == m.Name) is { } prop)
                            {
                                Collect(m.Node, prop.Use.TypeId);
                            }
                        }
                    }

                    break;
                }

                case TokenUnionOp t:
                    foreach (var b in t.Branches)
                    {
                        Collect(b.Node, domainTypeId);
                    }

                    break;
                case TaggedUnionOp tg:
                {
                    if (PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nested && nested.Definition.Id != def.Id)
                    {
                        found[nested.Definition.Id] = nested;
                    }

                    if (_project.Models.GetValueOrDefault(domainTypeId)?.Shape is UnionShape union)
                    {
                        foreach (var b in tg.Branches)
                        {
                            if (union.Variants.FirstOrDefault(v => v.Tag == b.Tag) is { } variant)
                            {
                                Collect(b.Node, variant.Use.TypeId);
                            }
                        }
                    }

                    break;
                }
            }
        }
    }

    private string ShapeExpression(string modelId)
    {
        if (!_project.Models.TryGetValue(modelId, out var model))
        {
            return $"new PrimitiveShape {{ PrimitiveId = Builtins.Scalar({PortableModel.Quote(modelId["std.".Length..])}) }}";
        }

        switch (model.Shape)
        {
            case ObjectShape shape:
            {
                var props = shape.Properties.Select(p => $"new DomainProperty {{ Name = {PortableModel.Quote(p.Name)}, Use = {UseExpression(p.Use)}, Presence = Presence.{p.Presence} }}");
                return $"new ObjectShape {{ Properties = [{string.Join(", ", props)}], Extension = new NoExtension() }}";
            }

            case ArrayShape array:
                return $"new ArrayShape {{ Element = {UseExpression(array.Element)} }}";
            case PrimitiveShape prim:
                return $"new PrimitiveShape {{ PrimitiveId = {PortableModel.Quote(prim.PrimitiveId)} }}";
            case UnionShape union:
            {
                var variants = union.Variants.Select(v => $"new UnionVariant {{ Tag = {PortableModel.Quote(v.Tag)}, Use = {UseExpression(v.Use)} }}");
                return $"new UnionShape {{ Variants = [{string.Join(", ", variants)}] }}";
            }

            default:
                return "throw new System.NotSupportedException(\"unsupported portable model shape\")";
        }
    }

    private string UseExpression(TypeUse use)
    {
        if (use.TypeId.StartsWith("std.", StringComparison.Ordinal))
        {
            var scalar = use.TypeId["std.".Length..];
            return use.SemanticNullable ? $"f.Builder.NullableScalar({PortableModel.Quote(scalar)})" : $"f.Builder.Scalar({PortableModel.Quote(scalar)})";
        }

        if (_project.Models.TryGetValue(use.TypeId, out var model))
        {
            if (model.Shape is ArrayShape array)
            {
                var inner = $"f.Builder.ArrayOf({PortableModel.Quote(model.Id)}, {PortableModel.Quote(model.TsName)}, {PortableModel.Quote(model.ClrIdentity)}, {UseExpression(array.Element)})";
                return use.SemanticNullable ? $"f.Builder.Nullable({inner})" : inner;
            }

            if (model.Shape is PrimitiveShape prim)
            {
                var scalar = PortableModel.ScalarName(prim.PrimitiveId);
                return use.SemanticNullable ? $"f.Builder.NullableScalar({PortableModel.Quote(scalar)})" : $"f.Builder.Scalar({PortableModel.Quote(scalar)})";
            }

        }

        // another portable definition (declared, or synthesized for a nested object/union model): its registration — a declared
        // dependency, so registered first — adds the model and codec <typeId>.codec with <typeId>.read/.write wires;
        // a nullable use wraps that codec's wires in a null branch
        var reference = $"new TypeUse {{ TypeId = {PortableModel.Quote(use.TypeId)}, CodecId = {PortableModel.Quote(use.TypeId + ".codec")}, SemanticNullable = false }}";
        return use.SemanticNullable ? $"f.Builder.Nullable({reference})" : reference;
    }

    /// <summary>A lambda body registering the wires of a program and returning the root wire ref.</summary>
    private string WireExpression(Program program, string domainTypeId, WireDirection direction, string rootId, string definitionId)
    {
        var statements = new List<string>();
        var root = EmitWire(program, domainTypeId, direction, rootId, statements, definitionId);
        return "{ " + string.Join(" ", statements) + " return " + root + "; }";
    }

    private string EmitWire(Program node, string domainTypeId, WireDirection direction, string id, List<string> statements, string definitionId)
    {
        var dir = direction == WireDirection.ServerRead ? "WireDirection.ServerRead" : "WireDirection.ServerWrite";
        switch (node)
        {
            case ScalarOp scalar:
            {
                var name = PortableModel.ScalarName(scalar.ScalarId);
                if (scalar.Representation == ScalarRepresentation.String)
                {
                    return $"f.StringWire({PortableModel.Quote(id)}, {dir}, Builtins.Grammar({PortableModel.Quote(name + "-string")}))";
                }

                return $"f.Scalar({PortableModel.Quote(name)}, {dir})";
            }

            case RefOp reference:
            {
                var target = PortableModel.Ref(_project, reference.DefinitionId);
                var targetModel = target?.Definition.Request?.DomainTypeId ?? target?.Definition.Response?.DomainTypeId ?? "unknown";
                var suffix = direction == WireDirection.ServerRead ? ".read" : ".write";
                return $"new WireRef {{ WireId = {PortableModel.Quote(targetModel + suffix)}, Direction = {dir} }}";
            }

            case NullableOp nullable:
            {
                var inner = EmitWire(nullable.Value, domainTypeId, direction, id + ".value", statements, definitionId);
                var nullId = direction == WireDirection.ServerRead ? "std.null.read" : "std.null.write";
                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(nullId)}, Direction = {dir}, Shape = new NullWire() }});");
                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(id)}, Direction = {dir}, Shape = new TokenUnionWire {{ Branches = [new TokenBranch {{ Token = JsonToken.Null, Wire = new WireRef {{ WireId = {PortableModel.Quote(nullId)}, Direction = {dir} }} }}, new TokenBranch {{ Token = JsonToken.{RootTokenName(nullable.Value)}, Wire = {inner} }}] }} }});");
                return $"new WireRef {{ WireId = {PortableModel.Quote(id)}, Direction = {dir} }}";
            }

            case ArrayOp array:
            {
                var elementType = _project.Models.TryGetValue(domainTypeId, out var m) && m.Shape is ArrayShape s ? s.Element.TypeId : domainTypeId;
                var element = EmitWire(array.Element, elementType, direction, id + ".element", statements, definitionId);
                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(id)}, Direction = {dir}, Shape = new ArrayWire {{ Element = {element} }} }});");
                return $"new WireRef {{ WireId = {PortableModel.Quote(id)}, Direction = {dir} }}";
            }

            case ObjectOp obj:
            {
                var model = _project.Models.GetValueOrDefault(domainTypeId);
                var suffix = direction == WireDirection.ServerRead ? ".read" : ".write";
                if (model is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nested && nested.Definition.Id != _currentDefinitionId)
                {
                    // the nested model's own registration declares its wire <modelId>.read/.write
                    return $"new WireRef {{ WireId = {PortableModel.Quote(domainTypeId + suffix)}, Direction = {dir} }}";
                }

                // an object model's wire is <modelId>.read/.write (the structural convention), so nested registrations and refs resolve it by name
                var wireId = model is null ? id : domainTypeId + suffix;
                var props = new List<string>();
                if (model is not null && PortableModel.VariantOf(_project, domainTypeId) is { } variant && PortableModel.DiscriminatorOf(_project, variant.Union.Id) is { } discriminator)
                {
                    // the variant's discriminator is a required literal wire of its tag, first in member order (SV13/SV50)
                    var litId = domainTypeId + ".tag" + suffix;
                    statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(litId)}, Direction = {dir}, Shape = new LiteralWire {{ Value = new JsonStringValue {{ Value = {PortableModel.Quote(variant.Tag)} }} }} }});");
                    props.Add($"new WireProperty {{ Name = {PortableModel.Quote(discriminator)}, Wire = new WireRef {{ WireId = {PortableModel.Quote(litId)}, Direction = {dir} }}, Presence = Presence.Required }}");
                }

                foreach (var member in obj.Members)
                {
                    var prop = (model?.Shape as ObjectShape)?.Properties.FirstOrDefault(p => p.Name == member.Name);
                    var memberWire = EmitWire(member.Node, prop?.Use.TypeId ?? domainTypeId, direction, wireId + ".members." + member.Name, statements, definitionId);
                    props.Add($"new WireProperty {{ Name = {PortableModel.Quote(member.Name)}, Wire = {memberWire}, Presence = Presence.{member.Presence} }}");
                }

                var additional = obj.UnknownMembers == UnknownMembers.Reject ? "new RejectAdditional()" : "new IgnoreAdditional()";
                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(wireId)}, Direction = {dir}, Shape = new ObjectWire {{ Properties = [{string.Join(", ", props)}], Additional = {additional}, DuplicatePolicyId = Builtins.DuplicatesReject, NameMatchingId = Builtins.NamesOrdinal }} }});");
                return $"new WireRef {{ WireId = {PortableModel.Quote(wireId)}, Direction = {dir} }}";
            }

            case TaggedUnionOp tagged:
            {
                var union = _project.Models.GetValueOrDefault(domainTypeId)?.Shape as UnionShape;
                var unionSuffix = direction == WireDirection.ServerRead ? ".read" : ".write";
                if (union is not null && PortableModel.DefinitionOfModel(_project, domainTypeId) is { } nestedUnion && nestedUnion.Definition.Id != _currentDefinitionId)
                {
                    return $"new WireRef {{ WireId = {PortableModel.Quote(domainTypeId + unionSuffix)}, Direction = {dir} }}";
                }

                var wireId = union is null ? id : domainTypeId + unionSuffix;
                var variants = new List<string>();
                var i = 0;
                foreach (var branch in tagged.Branches)
                {
                    var variantType = union?.Variants.FirstOrDefault(v => v.Tag == branch.Tag)?.Use.TypeId ?? domainTypeId;
                    var wire = EmitWire(branch.Node, variantType, direction, wireId + ".branches." + i++, statements, definitionId);
                    variants.Add($"new TaggedVariant {{ Tag = new StringTag {{ Value = {PortableModel.Quote(branch.Tag)} }}, Wire = {wire} }}");
                }

                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(wireId)}, Direction = {dir}, Shape = new TaggedUnionWire {{ Discriminator = {PortableModel.Quote(tagged.Discriminator)}, Variants = [{string.Join(", ", variants)}] }} }});");
                return $"new WireRef {{ WireId = {PortableModel.Quote(wireId)}, Direction = {dir} }}";
            }

            case TokenUnionOp union:
            {
                var branches = new List<string>();
                var i = 0;
                foreach (var branch in union.Branches)
                {
                    var wire = EmitWire(branch.Node, domainTypeId, direction, id + ".branches." + i++, statements, definitionId);
                    branches.Add($"new TokenBranch {{ Token = JsonToken.{branch.Token}, Wire = {wire} }}");
                }

                statements.Add($"f.Builder.AddWire(new Wire {{ Id = {PortableModel.Quote(id)}, Direction = {dir}, Shape = new TokenUnionWire {{ Branches = [{string.Join(", ", branches)}] }} }});");
                return $"new WireRef {{ WireId = {PortableModel.Quote(id)}, Direction = {dir} }}";
            }

            default:
                PortableModel.Unsupported(_bag, "/" + definitionId, $"unknown program op '{node.Op}'", definitionId);
                return $"new WireRef {{ WireId = {PortableModel.Quote(id)}, Direction = {dir} }}";
        }
    }

    private static string RootTokenName(Program program) => program switch
    {
        ScalarOp s when s.Representation == ScalarRepresentation.String => "String",
        ScalarOp s => PortableModel.ScalarName(s.ScalarId) switch
        {
            "boolean" => "Boolean",
            var n when Builtins.IsNumberTokenScalar(n) => "Number",
            _ => "String",
        },
        ObjectOp => "Object",
        ArrayOp => "Array",
        RefOp => "Object",
        _ => "Object",
    };
}
