#:property InvariantGlobalization=true
// Generates src/frontend/runtime/src/primitives/ordinalCasing.ts: .NET's OrdinalIgnoreCase as a code point table, so the TypeScript
// runtime matches property names, enum names and ignore-case keys exactly as System.Text.Json does (StringComparer.OrdinalIgnoreCase).
// Run from the repository root with the .NET SDK the server targets:  dotnet run scripts/generate-ordinal-casing.cs
// Every mapped pair is checked against string.Equals(..., StringComparison.OrdinalIgnoreCase) before the file is written.
using System.Globalization;
using System.Text;

var map = new List<(int From, int To)>();
for (var cp = 0; cp <= 0x10FFFF; cp++)
{
    if (cp is >= 0xD800 and <= 0xDFFF)
    {
        continue;
    }

    var s = char.ConvertFromUtf32(cp);
    var upper = s.ToUpperInvariant();
    if (upper == s)
    {
        continue;
    }

    if (char.ConvertFromUtf32(char.ConvertToUtf32(upper, 0)) != upper || !string.Equals(s, upper, StringComparison.OrdinalIgnoreCase))
    {
        throw new InvalidOperationException($"U+{cp:X4}: ToUpperInvariant gives '{upper}', which is not one code point equal under OrdinalIgnoreCase");
    }

    map.Add((cp, char.ConvertToUtf32(upper, 0)));
}

// runs of (start, count, stride, delta): consecutive or alternating code points shifted by the same amount
var runs = new List<(int Start, int Count, int Stride, int Delta)>();
for (var i = 0; i < map.Count;)
{
    var delta = map[i].To - map[i].From;
    var stride = 1;
    if (i + 1 < map.Count && map[i + 1].To - map[i + 1].From == delta && map[i + 1].From - map[i].From is 1 or 2)
    {
        stride = map[i + 1].From - map[i].From;
    }

    var count = 1;
    while (i + count < map.Count && map[i + count].From == map[i].From + count * stride && map[i + count].To - map[i + count].From == delta)
    {
        count++;
    }

    runs.Add((map[i].From, count, stride, delta));
    i += count;
}

var sb = new StringBuilder();
sb.Append("// Generated by scripts/generate-ordinal-casing.cs on .NET ").Append(Environment.Version).Append(" (invariant globalization). Do not edit.\n");
sb.Append("// ").Append(map.Count.ToString(CultureInfo.InvariantCulture)).Append(" code points in ").Append(runs.Count.ToString(CultureInfo.InvariantCulture)).Append(" runs, each checked against StringComparison.OrdinalIgnoreCase.\n\n");
sb.Append("/**\n");
sb.Append(" * .NET's OrdinalIgnoreCase, which System.Text.Json uses for case-insensitive property names and enum names: every\n");
sb.Append(" * code point maps to its simple uppercase from .NET's own Unicode tables — never to JavaScript's full mappings (ß → SS, ﬃ → FFI),\n");
sb.Append(" * and ı / ſ stay as they are. Runs of [start, count, stride, delta].\n");
sb.Append(" */\n");
sb.Append("const RUNS: readonly number[] = [\n");
foreach (var chunk in runs.Chunk(8))
{
    sb.Append("  ").AppendJoin(", ", chunk.Select(r => $"0x{r.Start:x}, {r.Count}, {r.Stride}, {r.Delta}")).Append(",\n");
}

sb.Append("];\n\n");
sb.Append("""
const UPPER: ReadonlyMap<number, number> = (() => {
  const map = new Map<number, number>();
  for (let i = 0; i < RUNS.length; i += 4) {
    for (let k = 0; k < RUNS[i + 1]!; k++) {
      const cp = RUNS[i]! + k * RUNS[i + 2]!;
      map.set(cp, cp + RUNS[i + 3]!);
    }
  }
  return map;
})();

/** The uppercase code point .NET's OrdinalIgnoreCase compares for `cp` (the code point itself when it has none). */
export function ordinalUpperCodePoint(cp: number): number {
  if (cp < 0x80) {
    return cp >= 0x61 && cp <= 0x7a ? cp - 32 : cp;
  }
  return UPPER.get(cp) ?? cp;
}

/** The text with every code point mapped as .NET's OrdinalIgnoreCase does (the UTF-16 length never changes). */
export function ordinalUpper(text: string): string {
  let out = "";
  for (const ch of text) {
    out += String.fromCodePoint(ordinalUpperCodePoint(ch.codePointAt(0)!));
  }
  return out;
}

/** `string.Equals(a, b, StringComparison.OrdinalIgnoreCase)`. */
export function ordinalEqualsIgnoreCase(a: string, b: string): boolean {
  return a === b || (a.length === b.length && ordinalUpper(a) === ordinalUpper(b));
}

""");

var target = Path.Combine("src", "frontend", "runtime", "src", "primitives", "ordinalCasing.ts");
File.WriteAllText(target, sb.ToString().Replace("\r\n", "\n", StringComparison.Ordinal));
Console.WriteLine($"wrote {target}: {map.Count} code points, {runs.Count} runs");
