// Generated by Tisilia portable codec generator 0.3. Type declarations of the self-contained module.
export interface PortableCodecContext { readonly path: string; }
export type PortableJsonValue = { kind: "null" } | { kind: "boolean"; value: boolean } | { kind: "string"; value: string } | { kind: "number"; text: string } | { kind: "array"; items: readonly PortableJsonValue[] } | { kind: "object"; entries: readonly { name: string; value: PortableJsonValue }[] };
export interface PortableDecimal { readonly kind: "decimal"; readonly sign: -1 | 1; readonly coefficient: bigint; readonly scale: number; }
export interface PortableDateOnly { readonly kind: "date-only"; readonly year: number; readonly month: number; readonly day: number; }
export interface PortableTimeOnly { readonly kind: "time-only"; readonly ticks: bigint; }
export interface PortableDateTimeUtc { readonly kind: "datetime-utc"; readonly ticks: bigint; }
export interface PortableDateTimeUnspecified { readonly kind: "datetime-unspecified"; readonly ticks: bigint; }
export interface PortableDateTimeLocalWire { readonly kind: "datetime-local-wire"; readonly ticks: bigint; readonly offsetMinutes: number; }
export interface PortableDateTimeOffset { readonly kind: "datetime-offset"; readonly ticks: bigint; readonly offsetMinutes: number; }
export interface PortableDuration { readonly kind: "duration"; readonly ticks: bigint; }
export interface Card {
  readonly "method": "card";
  readonly "last4": string;
}
export interface Cash {
  readonly "method": "cash";
}
export interface Circle {
  readonly "kind": "circle";
  readonly "radius": PortableDecimal;
  readonly "label"?: string | null;
}
export interface Customer {
  readonly "name": string;
  readonly "email": string | null;
  readonly "since": PortableDateOnly;
}
export interface Invoice {
  readonly "id": string;
  readonly "customer": Customer;
  readonly "total": PMoney;
  readonly "discount"?: PMoney | null;
  readonly "issued": PortableDateTimeOffset;
  readonly "due": PortableDateOnly;
  readonly "at": PortableTimeOnly;
  readonly "stamp": PortableDateTimeUtc;
  readonly "local": PortableDateTimeUnspecified;
  readonly "localWire": PortableDateTimeLocalWire;
  readonly "period": PortableDuration;
  readonly "ratio": number;
  readonly "weight": number;
  readonly "payload": Uint8Array;
  readonly "initial": string;
  readonly "shape": Shape;
  readonly "payment": Payment;
  readonly "lines": readonly (Line)[];
}
export interface Line {
  readonly "sku": string;
  readonly "qty": bigint;
  readonly "price": PortableDecimal;
}
export interface PMoney {
  readonly "amount": PortableDecimal;
  readonly "currency": string;
  readonly "note"?: string | null;
}
export type Payment = Card | Cash;
export interface Rect {
  readonly "kind": "rect";
  readonly "width": number;
  readonly "height": number;
  readonly "tags": readonly (string)[];
}
export type Shape = Circle | Rect;
export interface Tree {
  readonly "value": number;
  readonly "left": Tree | null;
  readonly "children": readonly (Tree)[];
}
export function cardDomainRule(value: unknown, context: PortableCodecContext): Card;
export const cardValidate: { validateDomain(value: unknown, context: PortableCodecContext): Card };
export const cardResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Card };
export const cardRequestEncode: { encodeRequest(value: Card, context: PortableCodecContext): PortableJsonValue };
export const cardRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Card };
export function cashDomainRule(value: unknown, context: PortableCodecContext): Cash;
export const cashValidate: { validateDomain(value: unknown, context: PortableCodecContext): Cash };
export const cashResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Cash };
export const cashRequestEncode: { encodeRequest(value: Cash, context: PortableCodecContext): PortableJsonValue };
export const cashRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Cash };
export function circleDomainRule(value: unknown, context: PortableCodecContext): Circle;
export const circleValidate: { validateDomain(value: unknown, context: PortableCodecContext): Circle };
export const circleResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Circle };
export const circleRequestEncode: { encodeRequest(value: Circle, context: PortableCodecContext): PortableJsonValue };
export const circleRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Circle };
export function customerDomainRule(value: unknown, context: PortableCodecContext): Customer;
export const customerValidate: { validateDomain(value: unknown, context: PortableCodecContext): Customer };
export const customerResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Customer };
export const customerRequestEncode: { encodeRequest(value: Customer, context: PortableCodecContext): PortableJsonValue };
export const customerRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Customer };
export function lineDomainRule(value: unknown, context: PortableCodecContext): Line;
export const lineValidate: { validateDomain(value: unknown, context: PortableCodecContext): Line };
export const lineResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Line };
export const lineRequestEncode: { encodeRequest(value: Line, context: PortableCodecContext): PortableJsonValue };
export const lineRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Line };
export function paymentDomainRule(value: unknown, context: PortableCodecContext): Payment;
export const paymentValidate: { validateDomain(value: unknown, context: PortableCodecContext): Payment };
export const paymentResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Payment };
export const paymentRequestEncode: { encodeRequest(value: Payment, context: PortableCodecContext): PortableJsonValue };
export const paymentRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Payment };
export function rectDomainRule(value: unknown, context: PortableCodecContext): Rect;
export const rectValidate: { validateDomain(value: unknown, context: PortableCodecContext): Rect };
export const rectResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Rect };
export const rectRequestEncode: { encodeRequest(value: Rect, context: PortableCodecContext): PortableJsonValue };
export const rectRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Rect };
export function invoiceDomainRule(value: unknown, context: PortableCodecContext): Invoice;
export const invoiceValidate: { validateDomain(value: unknown, context: PortableCodecContext): Invoice };
export const invoiceResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Invoice };
export const invoiceRequestEncode: { encodeRequest(value: Invoice, context: PortableCodecContext): PortableJsonValue };
export const invoiceRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Invoice };
export function pmoneyDomainRule(value: unknown, context: PortableCodecContext): PMoney;
export const pmoneyValidate: { validateDomain(value: unknown, context: PortableCodecContext): PMoney };
export const pmoneyResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): PMoney };
export const pmoneyRequestEncode: { encodeRequest(value: PMoney, context: PortableCodecContext): PortableJsonValue };
export const pmoneyRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): PMoney };
export function shapeDomainRule(value: unknown, context: PortableCodecContext): Shape;
export const shapeValidate: { validateDomain(value: unknown, context: PortableCodecContext): Shape };
export const shapeResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Shape };
export const shapeRequestEncode: { encodeRequest(value: Shape, context: PortableCodecContext): PortableJsonValue };
export const shapeRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Shape };
export function treeDomainRule(value: unknown, context: PortableCodecContext): Tree;
export const treeValidate: { validateDomain(value: unknown, context: PortableCodecContext): Tree };
export const treeResponseDecode: { decodeResponse(wire: PortableJsonValue, context: PortableCodecContext): Tree };
export const treeRequestEncode: { encodeRequest(value: Tree, context: PortableCodecContext): PortableJsonValue };
export const treeRequestInput: { parseRequestInput(input: string | PortableJsonValue, context: PortableCodecContext): Tree };
